#!/usr/bin/env python3
"""The fleet's settings, kept in this checkout's SQLite database fleet_config.sqlite; .env is generated from them.

  scripts/fleetcfg.py show                          the active profile: settings, robot slots, problems
  scripts/fleetcfg.py get KEY                       a setting's value (its default if the profile doesn't set it)
  scripts/fleetcfg.py set KEY=VALUE ...             change settings (and render .env); `unset KEY ...` = default
  scripts/fleetcfg.py robots N                      NUM_ROBOTS
  scripts/fleetcfg.py slot I MODEL [--pose X,Y,YAW | --no-pose]   slot I's model and spawn pose; `slot I --remove`
  scripts/fleetcfg.py render                        write .env (and the real-robot list) from the database
  scripts/fleetcfg.py profile list | use NAME | new NAME [--from P] | rename OLD NEW | delete NAME
                              | notes NAME TEXT | export [NAME] | import FILE [--name NAME]
  scripts/fleetcfg.py history [-n N] | revert ID    the change log (who changed what, when); undo one change
  scripts/fleetcfg.py runs [-n N]                   sim starts and spawns (scripts/fleet.sh) and what they ran with
  scripts/fleetcfg.py real list | set ID [--host H] [--user U] [--cutter | --no-cutter] | remove ID
  scripts/fleetcfg.py import-env FILE [--profile NAME]   load an old-style .env into a profile
  scripts/fleetcfg.py check                         the catalog's defaults vs. docker-compose.yml's

What each setting means is scripts/fleet_settings.py; the tables are scripts/fleet_config_migrations/ (applied
here on first open). Every checkout has its own database file, so any PC runs the fleet right after a clone,
with no server (FLEET_CONFIG_DB=<file> picks another, e.g. a scratch one for tests). Its first use imports, in
this order: the PostgreSQL fleet_config a running base station held before 2026-10-10 (with psycopg installed),
else the existing .env (or the last one committed to git) and tools/sim_ui/real_robots.json, else the defaults.
Stdlib only (psycopg just for that import); tools/sim_ui/server.py imports this module.
"""
import argparse
import datetime
import getpass
import json
import math
import os
import re
import socket
import sqlite3
import subprocess
import sys
import tempfile
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import fleet_settings as cat  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
ENV_FILE = ROOT / ".env"
# The real-robot list as last read from the database (the web UI's fallback if the database can't be opened).
REAL_FILE = ROOT / "tools/sim_ui/real_robots.json"
HEADER = "# GENERATED by scripts/fleetcfg.py"
MIGRATIONS = ROOT / "scripts/fleet_config_migrations"
BASESTATION = "basestation"
GENERIC_SLOT_MODEL = "a300"  # a slot with no row (docker-compose.yml's ${ROBOT_MODEL_<i>:-a300})


def _db_file():
    v = os.environ.get("FLEET_CONFIG_DB")
    if not v:
        return ROOT / "fleet_config.sqlite"
    if "/" in v:
        return Path(v)
    return ROOT / (v if v.endswith((".sqlite", ".db")) else v + ".sqlite")  # a bare name: a file next to .env


DB_FILE = _db_file()


class Unavailable(RuntimeError):
    """The database file can't be opened or set up (permissions, a failed migration)."""


def default_actor():
    return f"{getpass.getuser()}@{socket.gethostname()}"


def now_iso():
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


def to_iso(t):
    """A datetime (from PostgreSQL) as the database's UTC ISO text."""
    if t is None or isinstance(t, str):
        return t
    return t.astimezone(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


def from_iso(s):
    return datetime.datetime.fromisoformat(s.replace("Z", "+00:00")) if s else None


# ---------------------------------------------------------------- .env files

def parse_env(text):
    """KEY=VALUE lines as docker compose reads them (last one wins; surrounding quotes removed)."""
    out = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        k, v = k.strip().removeprefix("export ").strip(), v.strip()
        if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":
            v = v[1:-1]
        out[k] = v
    return out


def read_env_file(path=ENV_FILE):
    try:
        return parse_env(path.read_text())
    except OSError:
        return {}


def env_is_generated(path=ENV_FILE):
    try:
        with open(path) as f:
            return f.readline().startswith(HEADER)
    except OSError:
        return False


def write_if_changed(path, text):
    try:
        if path.read_text() == text:
            return False
    except OSError:
        pass
    # a unique temporary file: the web UI renders from several threads at once
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name.lstrip('.')}.", suffix=".tmp")
    with os.fdopen(fd, "w") as f:
        f.write(text)
    os.chmod(tmp, 0o644)
    os.replace(tmp, path)  # atomic: compose never reads half a file
    return True


def git(*args):
    p = subprocess.run(["git", "-C", str(ROOT), *args], capture_output=True, text=True)
    return p.stdout if p.returncode == 0 else None


def from_git_history(rel):
    """A file's last committed content (before it was untracked), for the first-use import on a fresh checkout."""
    commit = (git("log", "-1", "--format=%H", "--", rel) or "").strip()
    if not commit:
        return None, None
    for rev in (commit, commit + "^"):  # the commit that untracked it has it only in its parent
        text = git("show", f"{rev}:{rel}")
        if text is not None:
            return text, f"git {rev[:9]}"
    return None, None


# ---------------------------------------------------------------- database

def _statements(sql):
    """A migration file's statements, one by one (executescript would commit the open transaction)."""
    out, cur = [], ""
    for line in sql.splitlines(keepends=True):
        cur += line
        if sqlite3.complete_statement(cur):
            out.append(cur)
            cur = ""
    if any(l.strip() and not l.strip().startswith("--") for l in cur.splitlines()):
        out.append(cur)  # an unterminated last statement: let SQLite report it
    return out


def _migrate(conn):
    """Apply scripts/fleet_config_migrations/*.sql not yet in schema_migrations, each in one transaction."""
    conn.execute("CREATE TABLE IF NOT EXISTS schema_migrations (version text PRIMARY KEY, "
                 "applied_at text NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')))")
    done = {r[0] for r in conn.execute("SELECT version FROM schema_migrations")}
    for f in sorted(MIGRATIONS.glob("*.sql")):
        if f.stem in done:
            continue
        conn.execute("BEGIN IMMEDIATE")
        try:
            if not conn.execute("SELECT 1 FROM schema_migrations WHERE version = ?", (f.stem,)).fetchone():
                for statement in _statements(f.read_text()):
                    conn.execute(statement)
                conn.execute("INSERT INTO schema_migrations (version) VALUES (?)", (f.stem,))
            conn.execute("COMMIT")
        except sqlite3.Error as e:
            conn.execute("ROLLBACK")
            raise Unavailable(f"{DB_FILE}: migration {f.name} failed ({e})") from None


CONSTRAINTS = {  # scripts/fleet_config_migrations/: what a violation means
    "profile.name": "there is a profile with that name already",
    "length(name)": "a profile name is letters, digits, spaces, '.', '_' and '-' (up to 63)",
    "id GLOB": "a real robot id looks like j100_0921",
    "model GLOB": "a model id looks like a300 or j100_0921",
}

# Primary keys and columns of the logged tables (change_log rows hold whole rows as JSON).
TABLE_KEYS = {"profile": ("id",), "active_profile": ("only_row",), "setting_value": ("profile_id", "key"),
              "robot_slot": ("profile_id", "slot"), "real_robot": ("id",)}
COLUMNS = {"profile": ("id", "name", "notes", "created_at"), "active_profile": ("only_row", "profile_id"),
           "setting_value": ("profile_id", "key", "value"),
           "robot_slot": ("profile_id", "slot", "model", "x", "y", "yaw_deg"),
           "real_robot": ("id", "host", "ssh_user", "cutter")}
BULK_TABLES = ("setting_value", "robot_slot")  # not logged row by row while a whole profile is created/deleted


class DB:
    """One connection, one write transaction: `with DB() as db:` commits at the end, rolls back on an exception.
    BEGIN IMMEDIATE serialises writers (the web UI's threads and the command line); WAL keeps readers going."""

    def __init__(self, actor=None):
        self.actor = actor or default_actor()
        self.bulk = False
        try:
            self.conn = sqlite3.connect(str(DB_FILE), timeout=15, isolation_level=None)
            self.conn.execute("PRAGMA foreign_keys = ON")
            if self.conn.execute("PRAGMA journal_mode").fetchone()[0] != "wal":
                self.conn.execute("PRAGMA journal_mode = WAL")
            _migrate(self.conn)
            self.conn.execute("BEGIN IMMEDIATE")
        except sqlite3.Error as e:
            raise Unavailable(f"settings database {DB_FILE}: {e}") from None
        self.cur = self.conn.cursor()

    def q(self, sql, args=()):
        self.cur.execute(sql, args)
        return self.cur

    def all(self, sql, args=()):
        return self.q(sql, args).fetchall()

    def one(self, sql, args=()):
        return self.q(sql, args).fetchone()

    def val(self, sql, args=()):
        row = self.one(sql, args)
        return row[0] if row else None

    def dicts(self, sql, args=()):
        cur = self.q(sql, args)
        cols = [d[0] for d in cur.description]
        return [dict(zip(cols, r)) for r in cur.fetchall()]

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        try:
            self.conn.execute("COMMIT" if exc_type is None else "ROLLBACK")
        finally:
            self.conn.close()
        if isinstance(exc, sqlite3.IntegrityError):  # a constraint (name taken, bad model id...): the caller's mistake
            msg = str(exc)
            for constraint, text in CONSTRAINTS.items():
                if constraint in msg:
                    msg = text
            raise ValueError(msg) from exc


def _row(db, table, key):
    keys = TABLE_KEYS[table]
    rows = db.dicts(f"SELECT {', '.join(COLUMNS[table])} FROM {table} WHERE "
                    + " AND ".join(f"{k} = ?" for k in keys), [key[k] for k in keys])
    return rows[0] if rows else None


def _log(db, table, op, old, new):
    if (db.bulk and table in BULK_TABLES) or old == new:
        return
    db.q("INSERT INTO change_log (actor, tbl, op, old_row, new_row) VALUES (?, ?, ?, ?, ?)",
         (db.actor, table, op, None if old is None else json.dumps(old), None if new is None else json.dumps(new)))


def _put(db, table, row):
    """Insert or update one row by its primary key, and log the change."""
    keys = TABLE_KEYS[table]
    old = _row(db, table, row)
    cols = [c for c in COLUMNS[table] if c in row]
    db.q(f"INSERT INTO {table} ({', '.join(cols)}) VALUES ({', '.join('?' * len(cols))}) "
         f"ON CONFLICT ({', '.join(keys)}) DO UPDATE SET "
         + ", ".join(f"{c} = excluded.{c}" for c in cols if c not in keys), [row[c] for c in cols])
    new = _row(db, table, row)
    _log(db, table, "INSERT" if old is None else "UPDATE", old, new)
    return new


def _delete(db, table, key):
    old = _row(db, table, key)
    if old is None:
        return False
    keys = TABLE_KEYS[table]
    db.q(f"DELETE FROM {table} WHERE " + " AND ".join(f"{k} = ?" for k in keys), [key[k] for k in keys])
    _log(db, table, "DELETE", old, None)
    return True


def _note(db, text):
    """A change log line that is not a row change (an import)."""
    db.q("INSERT INTO change_log (actor, tbl, op, new_row) VALUES (?, 'import', 'IMPORT', ?)",
         (db.actor, json.dumps({"source": text})))


# ---------------------------------------------------------------- the PostgreSQL fleet_config, once

def running_pg():
    """PGPORT/PGUSER of the running base station container ({} if it isn't running or docker isn't there)."""
    try:
        p = subprocess.run(["docker", "inspect", "-f", "{{if .State.Running}}{{range .Config.Env}}{{println .}}"
                            "{{end}}{{end}}", BASESTATION], capture_output=True, text=True, timeout=10)
    except (OSError, subprocess.TimeoutExpired):
        return {}
    return dict(line.split("=", 1) for line in p.stdout.splitlines() if line.startswith(("PGPORT=", "PGUSER=")))


def _import_postgres(db):
    """Copy the PostgreSQL fleet_config a running base station held (2026-10-09/10) whole: profiles, settings,
    slots, real robots, the change log and runs, ids kept. None if there is none to reach (no psycopg, the base
    station not running here, no such database, or it has no profile)."""
    if os.environ.get("FLEET_NO_PG_IMPORT"):
        return None
    try:
        import psycopg as drv
    except ImportError:
        try:
            import psycopg2 as drv
        except ImportError:
            return None
    pg = running_pg()
    if not pg:
        return None
    env, secrets = read_env_file(), read_env_file(ROOT / "db.env")
    try:
        pc = drv.connect(host="127.0.0.1", port=int(pg.get("PGPORT") or env.get("BASESTATION_PG_PORT") or 5433),
                         user=pg.get("PGUSER") or "admin", dbname="fleet_config", connect_timeout=3,
                         password=secrets.get("PGPASSWORD") or os.environ.get("PGPASSWORD", ""))
    except drv.Error:
        return None
    try:
        cur = pc.cursor()

        def rows(sql):
            cur.execute(sql)
            cols = [d[0] for d in cur.description]
            return [dict(zip(cols, r)) for r in cur.fetchall()]
        try:
            profs = rows("SELECT id, name, notes, created_at FROM profile ORDER BY id")
        except drv.Error:
            return None
        if not profs:
            return None
        for p in profs:
            db.q("INSERT INTO profile (id, name, notes, created_at) VALUES (?, ?, ?, ?)",
                 (p["id"], p["name"], p["notes"], to_iso(p["created_at"])))
        for r in rows("SELECT profile_id, key, value FROM setting_value"):
            db.q("INSERT INTO setting_value (profile_id, key, value) VALUES (?, ?, ?)",
                 (r["profile_id"], r["key"], r["value"]))
        for r in rows("SELECT profile_id, slot, model, x, y, yaw_deg FROM robot_slot"):
            db.q("INSERT INTO robot_slot (profile_id, slot, model, x, y, yaw_deg) VALUES (?, ?, ?, ?, ?, ?)",
                 (r["profile_id"], r["slot"], r["model"], r["x"], r["y"], r["yaw_deg"]))
        for r in rows("SELECT profile_id FROM active_profile"):
            db.q("INSERT INTO active_profile (only_row, profile_id) VALUES (1, ?)", (r["profile_id"],))
        for r in rows("SELECT id, host, ssh_user, cutter FROM real_robot"):
            db.q("INSERT INTO real_robot (id, host, ssh_user, cutter) VALUES (?, ?, ?, ?)",
                 (r["id"], r["host"], r["ssh_user"], int(bool(r["cutter"]))))
        log = rows("SELECT id, at, actor, tbl, op, old_row, new_row FROM change_log ORDER BY id")
        for r in log:
            db.q("INSERT INTO change_log (id, at, actor, tbl, op, old_row, new_row) VALUES (?, ?, ?, ?, ?, ?, ?)",
                 (r["id"], to_iso(r["at"]), r["actor"], r["tbl"], r["op"],
                  None if r["old_row"] is None else json.dumps(r["old_row"]),
                  None if r["new_row"] is None else json.dumps(r["new_row"])))
        runs_ = rows("SELECT id, started_at, finished_at, actor, command, profile, git_commit, env, exit_code FROM run")
        for r in runs_:
            db.q("INSERT INTO run (id, started_at, finished_at, actor, command, profile, git_commit, env, exit_code) "
                 "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
                 (r["id"], to_iso(r["started_at"]), to_iso(r["finished_at"]), r["actor"], r["command"],
                  r["profile"], r["git_commit"], json.dumps(r["env"]), r["exit_code"]))
        if not db.val("SELECT 1 FROM active_profile"):
            db.q("INSERT INTO active_profile (only_row, profile_id) VALUES (1, ?)", (profs[0]["id"],))
        return (f"the base station's PostgreSQL fleet_config ({len(profs)} profile(s), {len(log)} change(s), "
                f"{len(runs_)} run(s))")
    finally:
        pc.close()


# ---------------------------------------------------------------- the active profile

def slot_ns(model, slot):
    """Container name / ROS namespace: a real robot's own id, else <model>_<slot %04d> (docker-compose.yml)."""
    return model if "_" in model else f"{model}_{slot:04d}"


def import_env_vals(vals):
    """An old-style .env's variables -> (settings, slots, notes). Derived variables are dropped (render makes them)."""
    settings, slots, notes = {}, {}, []
    for k, v in vals.items():
        m = re.fullmatch(r"ROBOT_(MODEL|POSE)_(\d+)", k)
        if m:
            i = int(m[2])
            if i >= cat.MAX_SLOTS:
                notes.append(f"{k}: no slot {i} (0-{cat.MAX_SLOTS - 1})")
                continue
            s = slots.setdefault(i, {"model": GENERIC_SLOT_MODEL, "x": None, "y": None, "yaw": None})
            if m[1] == "MODEL":
                if not re.fullmatch(r"[a-z0-9]+(_[0-9]+)?", v):
                    notes.append(f"{k}={v}: not a model id, slot {i} left {s['model']}")
                else:
                    s["model"] = v
            else:
                try:
                    x, y, yaw = (float(p) for p in v.split(","))
                    s.update(x=x, y=y, yaw=yaw)
                except ValueError:
                    notes.append(f"{k}={v}: not x,y,yaw")
            continue
        if cat.is_derived(k):
            continue
        if not re.fullmatch(r"[A-Z][A-Z0-9_]*", k) or cat.is_reserved(k):
            notes.append(f"{k}: not a setting name, skipped")
            continue
        err = cat.check_value(k, v)
        if err:
            notes.append(f"{k}={v}: skipped, must be {err}")
            continue
        settings[k] = v
    return settings, slots, notes


def _create_profile(db, name, settings, slots, notes=""):
    db.bulk = True  # the change log gets the profile, not each of its settings and slots
    pid = db.val("INSERT INTO profile (name, notes) VALUES (?, ?) RETURNING id", (name, notes))
    _log(db, "profile", "INSERT", None, _row(db, "profile", {"id": pid}))
    for k, v in settings.items():
        _put(db, "setting_value", {"profile_id": pid, "key": k, "value": v})
    for i, s in slots.items():
        _put(db, "robot_slot", {"profile_id": pid, "slot": i, "model": s["model"], "x": s.get("x"),
                                "y": s.get("y"), "yaw_deg": s.get("yaw")})
    return pid


def _first_use(db):
    """No profile yet: import the base station's old PostgreSQL fleet_config if it can be reached, else this
    checkout's .env (hand-written from before the database, or generated: the newest state either way), else
    the last one committed to git, and real_robots.json."""
    source = _import_postgres(db)
    if source:
        _note(db, source)
        print(f"[fleetcfg] first use of {DB_FILE.name}: imported {source}", file=sys.stderr)
        return
    notes = []
    if ENV_FILE.exists():
        text, source = ENV_FILE.read_text(), "the .env file"
    else:
        text, source = from_git_history(".env")
    if text is None:
        settings, slots, source = {}, {}, "defaults"
    else:
        settings, slots, notes = import_env_vals(parse_env(text))
    pid = _create_profile(db, "default", settings, slots, f"imported from {source}")
    _put(db, "active_profile", {"only_row": 1, "profile_id": pid})
    if not db.val("SELECT count(*) FROM real_robot"):
        try:
            real = json.loads(REAL_FILE.read_text())
        except (OSError, ValueError):
            text, _ = from_git_history(str(REAL_FILE.relative_to(ROOT)))
            real = json.loads(text) if text else {}
        for rid, c in real.items():
            if re.fullmatch(r"[a-z0-9]+_[0-9]+", rid) and isinstance(c, dict):
                _put(db, "real_robot", {"id": rid, "host": c.get("host") or f"cpr-{rid.replace('_', '-')}.local",
                                        "ssh_user": c.get("user") or "robot", "cutter": int(bool(c.get("cutter")))})
    _note(db, source)
    for n in notes:
        print(f"[fleetcfg] import: {n}", file=sys.stderr)
    print(f"[fleetcfg] first use of {DB_FILE.name}: profile 'default' imported from {source}", file=sys.stderr)


def active(db):
    """(id, name) of the active profile; the first use of the database imports one (BEGIN IMMEDIATE: one at a time)."""
    row = db.one("SELECT p.id, p.name FROM active_profile a JOIN profile p ON p.id = a.profile_id")
    if row:
        return row
    first = db.one("SELECT id, name FROM profile ORDER BY id LIMIT 1")
    if first:
        _put(db, "active_profile", {"only_row": 1, "profile_id": first[0]})
        return first
    _first_use(db)
    return db.one("SELECT p.id, p.name FROM active_profile a JOIN profile p ON p.id = a.profile_id")


def profile_id(db, name):
    pid = db.val("SELECT id FROM profile WHERE name = ?", (name,))
    if pid is None:
        raise ValueError(f"no profile {name!r}")
    return pid


def load(db, pid=None):
    """{profile, settings: {key: value}, slots: {i: {model, x, y, yaw}}} of a profile (the active one by default)."""
    if pid is None:
        pid, name = active(db)
    else:
        name = db.val("SELECT name FROM profile WHERE id = ?", (pid,))
    settings = dict(db.all("SELECT key, value FROM setting_value WHERE profile_id = ? ORDER BY key", (pid,)))
    slots = {r[0]: {"model": r[1], "x": r[2], "y": r[3], "yaw": r[4]} for r in
             db.all("SELECT slot, model, x, y, yaw_deg FROM robot_slot WHERE profile_id = ? ORDER BY slot", (pid,))}
    return {"profile_id": pid, "profile": name, "settings": settings, "slots": slots}


def default_cfg():
    return {"profile_id": None, "profile": None, "settings": {}, "slots": {}}


def effective(cfg, key):
    v = cfg["settings"].get(key)
    if v is None and key in cat.BY_KEY:
        v = cat.BY_KEY[key]["default"]
    return v


def num_robots(cfg):
    try:
        return int(effective(cfg, "NUM_ROBOTS") or 0)
    except ValueError:
        return 0


def linked_real_robots(cfg, real):
    """{id: endpoint} of the real robots the base station's zenoh router dials (BASESTATION_ZENOH_CONNECT has
    tcp/<their host>:7447). The router routes between everything it dials, the sim's zenoh-router included, so
    such a robot shares one ROS graph with the sim, whether it is on now or powers on later."""
    if (effective(cfg, "BASESTATION_RMW") or effective(cfg, "FLEET_RMW")) != "rmw_zenoh_cpp":
        return {}
    endpoints = set((effective(cfg, "BASESTATION_ZENOH_CONNECT") or "").split())
    return {r["id"]: f"tcp/{r['host']}:7447" for r in real or () if f"tcp/{r['host']}:7447" in endpoints}


def problems(cfg, real=None):
    """(errors, warnings): errors stop render (compose would fail or the sim reject the spawn). real: the
    real_robot rows (the sim/real clash check needs their hosts)."""
    errors, warnings = [], []
    n = num_robots(cfg)
    if not 0 <= n <= cat.MAX_SLOTS:
        errors.append(f"NUM_ROBOTS={n}: 0-{cat.MAX_SLOTS}")
        n = 0
    seen = {}
    linked = linked_real_robots(cfg, real)
    for i in range(n):
        model = cfg["slots"].get(i, {}).get("model", GENERIC_SLOT_MODEL)
        ns = slot_ns(model, i)
        if ns in seen:
            errors.append(f"slots {seen[ns]} and {i} are both {ns}: one real robot can only be in one slot")
        seen[ns] = i
        if model in linked:
            # the sim robot would publish the real one's topics (cmd_vel, arm goals) into the graph the real one
            # joins through the base station, and the real robot would answer the sim robot's tools
            errors.append(f"slot {i} is the real robot {model}, which the base station's router dials "
                          f"({linked[model]}): the sim robot would share its ROS names, and commands meant for "
                          f"one could reach the other. Unlink {model} (Base station card, or "
                          f"BASESTATION_ZENOH_CONNECT), or give slot {i} another model")
        if "_" in model and not (ROOT / "robot_data" / model / "robot.yaml").exists():
            warnings.append(f"slot {i} ({model}): no robot_data/{model}/robot.yaml, its container exits at once")
        if not (ROOT / "sim/assets" / model / f"{model}.urdf").exists():
            warnings.append(f"slot {i}: no sim model sim/assets/{model}/ (scripts/gen_urdf.sh)")
    for k, v in cfg["settings"].items():
        if cat.is_reserved(k):
            errors.append(f"{k}: docker compose's own variable, not a setting (scripts/fleetcfg.py unset {k})")
            continue
        err = cat.check_value(k, v)
        if err:
            errors.append(f"{k}={v}: must be {err}")
    return errors, warnings


def _env_value(v):
    return f'"{v}"' if re.search(r"[\s#]", v) else v


def render_text(cfg, source):
    """The .env text for a profile: its settings (unset ones are left to compose's defaults) and the slots.
    No timestamp: the same settings give the same text, so .env is only rewritten when they change."""
    lines = [f"{HEADER} from {source} -- do not edit: changes are overwritten.",
             "# Change settings in the web UI (tools/sim_ui, Configuration) or with scripts/fleetcfg.py set KEY=VALUE.",
             f"# Profile: {cfg['profile'] or '(none: database unusable, defaults)'}."]
    settings = dict(cfg["settings"])
    settings.setdefault("NUM_ROBOTS", cat.BY_KEY["NUM_ROBOTS"]["default"])
    for section in cat.SECTIONS:
        keys = [s["key"] for s in cat.SETTINGS if s["section"] == section and s["key"] in settings]
        if keys:
            lines += ["", f"# {section}"] + [f"{k}={_env_value(settings[k])}" for k in keys]
    other = sorted(k for k in settings if k not in cat.BY_KEY)
    if other:
        lines += ["", "# Not in scripts/fleet_settings.py"] + [f"{k}={_env_value(settings[k])}" for k in other]
    n = num_robots(cfg)
    lines += ["", "# Robot slots: compose profile n<NUM_ROBOTS> starts slots 0..N-1; container name, hostname",
              "# and namespace follow each slot's model (see docker-compose.yml)", f"COMPOSE_PROFILES=n{n}"]
    for i in range(cat.MAX_SLOTS):
        s = cfg["slots"].get(i)
        model = s["model"] if s else GENERIC_SLOT_MODEL
        if s:
            lines.append(f"ROBOT_MODEL_{i}={model}")
            if s.get("x") is not None:
                lines.append(f"ROBOT_POSE_{i}={s['x']:g},{s['y']:g},{s['yaw']:g}")
        if "_" in model:
            lines.append(f"ROBOT_SUFFIX_{i}=")
        lines.append(f"ROBOT_HOSTNAME_{i}=cpr-{slot_ns(model, i).replace('_', '-')}")
    return "\n".join(lines) + "\n"


def _real_rows(db):
    return [dict(r, cutter=bool(r["cutter"]))
            for r in db.dicts("SELECT id, host, ssh_user AS user, cutter FROM real_robot ORDER BY id")]


def _write_real_file(rows):
    data = {r["id"]: {"host": r["host"], **({"user": r["user"]} if r["user"] != "robot" else {}),
                      "cutter": r["cutter"]} for r in rows}
    write_if_changed(REAL_FILE, json.dumps(data, indent=2) + "\n")


def render(actor=None, db=None):
    """Write .env (and the real-robot list) from the active profile. Returns {source, profile, changed, errors,
    warnings, why}: source "database", or "offline" (the database file can't be opened: .env kept, or made from
    the defaults if there is none). Errors: nothing written."""
    try:
        if db is None:
            with DB(actor) as own:
                return render(actor, own)
        cfg = load(db)
        real = _real_rows(db)
    except Unavailable as e:
        r = {"source": "offline", "why": str(e), "profile": None, "errors": [], "warnings": [], "changed": False}
        if not ENV_FILE.exists():
            r["changed"] = write_if_changed(ENV_FILE, render_text(default_cfg(), "the defaults (no database)"))
        return r
    errors, warnings = problems(cfg, real)
    r = {"source": "database", "why": "", "profile": cfg["profile"], "errors": errors, "warnings": warnings,
         "changed": False}
    if not errors:
        r["changed"] = write_if_changed(ENV_FILE, render_text(cfg, DB_FILE.name))
        _write_real_file(real)
    return r


LAST_RENDER = {}  # env()'s last render(): where .env came from (the web UI's header shows it)


def env(actor=None):
    """The variables compose sees: .env rendered fresh from the database (as it is if the file can't be opened)."""
    global LAST_RENDER
    LAST_RENDER = render(actor)  # rebound, not updated in place: other threads read it
    return read_env_file()


# ---------------------------------------------------------------- changes

def set_settings(updates, actor=None):
    """{key: value or None (= back to the default)} into the active profile, then render. Values already in effect
    are skipped, so a caller that rewrites unchanged values works even if the database can't be opened."""
    current = read_env_file()
    for k, v in updates.items():
        if not re.fullmatch(r"[A-Z][A-Z0-9_]*", k) or cat.is_derived(k):
            raise ValueError(f"{k}: not a setting (robot slots: scripts/fleetcfg.py slot / robots)")
        if cat.is_reserved(k):
            raise ValueError(f"{k}: docker compose's own variable, not a fleet setting")
        if v is not None:
            err = cat.check_value(k, str(v))
            if err:
                raise ValueError(f"{k} must be {err}")
        s = cat.BY_KEY.get(k)
        if s and s["fixed"] and (str(v) if v is not None else s["default"]) != current.get(k, s["default"]):
            raise ValueError(f"{k} is set when the base station's database is first created: changed later, the "
                             f"base station could no longer log in to it")
    unchanged = all(v is not None and (current[k] if k in current else cat.BY_KEY.get(k, {}).get("default")) == str(v)
                    for k, v in updates.items())
    try:
        with DB(actor) as db:
            pid, _ = active(db)
            for k, v in updates.items():
                if v is None:
                    _delete(db, "setting_value", {"profile_id": pid, "key": k})
                else:
                    _put(db, "setting_value", {"profile_id": pid, "key": k, "value": str(v)})
            r = render(actor, db)
            if r["errors"]:
                raise ValueError("; ".join(r["errors"]))
            return r
    except Unavailable as e:
        if unchanged:  # nothing to change: .env already says so
            return {"source": "offline", "why": str(e), "changed": False, "errors": [], "warnings": []}
        raise


def _pose(p):
    if p is None:
        return None, None, None
    vals = [float(p.get(k)) for k in ("x", "y", "yaw")]
    if not all(math.isfinite(v) for v in vals):
        raise ValueError("pose values must be finite numbers")
    return tuple(vals)


def _put_slot(db, pid, i, model, x, y, yaw):
    _put(db, "robot_slot", {"profile_id": pid, "slot": i, "model": model, "x": x, "y": y, "yaw_deg": yaw})


def set_slots(robots, actor=None, num_robots=None):
    """Slots 0..len-1 from [{model, x?, y?, yaw?} or None (= forget the slot)], a pose with all three or none;
    rows of higher slots are kept. NUM_ROBOTS too if given. Then render. If the database can't be opened, a
    request that changes no model and no NUM_ROBOTS passes (a spawn hands its poses to the sim itself)."""
    if len(robots) > cat.MAX_SLOTS:
        raise ValueError(f"at most {cat.MAX_SLOTS} robots")
    if num_robots is not None and not 0 <= int(num_robots) <= cat.MAX_SLOTS:
        raise ValueError(f"NUM_ROBOTS 0-{cat.MAX_SLOTS}")
    rows = []
    for i, r in enumerate(robots):
        if r is None:
            rows.append(None)
            continue
        model = r.get("model") or GENERIC_SLOT_MODEL
        if not re.fullmatch(r"[a-z0-9]+(_[0-9]+)?", model):
            raise ValueError(f"slot {i}: {model!r} is not a model id")
        has_pose = all(r.get(k) not in (None, "") for k in ("x", "y", "yaw"))
        rows.append((model, *_pose(r if has_pose else None)))
    current = read_env_file()
    unchanged = (num_robots is None or current.get("NUM_ROBOTS") == str(num_robots)) and all(
        row is not None and current.get(f"ROBOT_MODEL_{i}") == row[0] for i, row in enumerate(rows))
    try:
        with DB(actor) as db:
            pid, _ = active(db)
            for i, row in enumerate(rows):
                if row is None:
                    _delete(db, "robot_slot", {"profile_id": pid, "slot": i})
                else:
                    _put_slot(db, pid, i, *row)
            if num_robots is not None:
                _put(db, "setting_value", {"profile_id": pid, "key": "NUM_ROBOTS", "value": str(int(num_robots))})
            r = render(actor, db)
            if r["errors"]:
                raise ValueError("; ".join(r["errors"]))
            return r
    except Unavailable as e:
        if unchanged:
            return {"source": "offline", "why": str(e), "changed": False, "errors": [], "warnings": []}
        raise


def set_slot(i, model=None, pose=None, clear_pose=False, remove=False, actor=None):
    if not 0 <= i < cat.MAX_SLOTS:
        raise ValueError(f"slot 0-{cat.MAX_SLOTS - 1}")
    with DB(actor) as db:
        pid, _ = active(db)
        if remove:
            _delete(db, "robot_slot", {"profile_id": pid, "slot": i})
        else:
            cur = load(db, pid)["slots"].get(i, {"model": GENERIC_SLOT_MODEL, "x": None, "y": None, "yaw": None})
            model = model or cur["model"]
            if not re.fullmatch(r"[a-z0-9]+(_[0-9]+)?", model):
                raise ValueError(f"{model!r} is not a model id")
            x, y, yaw = (None, None, None) if clear_pose else _pose(pose) if pose else (cur["x"], cur["y"], cur["yaw"])
            _put_slot(db, pid, i, model, x, y, yaw)
        r = render(actor, db)
        if r["errors"]:
            raise ValueError("; ".join(r["errors"]))
        return r


# ---------------------------------------------------------------- profiles

def profiles(db):
    return [dict(r, active=bool(r["active"])) for r in db.dicts(
        "SELECT p.id, p.name, p.notes, p.created_at, (a.profile_id IS NOT NULL) AS active, "
        "(SELECT count(*) FROM setting_value s WHERE s.profile_id = p.id) AS settings, "
        "(SELECT value FROM setting_value s WHERE s.profile_id = p.id AND key = 'NUM_ROBOTS') AS num_robots "
        "FROM profile p LEFT JOIN active_profile a ON a.profile_id = p.id ORDER BY p.name")]


def profile_new(name, from_name=None, notes="", actor=None):
    with DB(actor) as db:
        src = profile_id(db, from_name) if from_name else active(db)[0]
        cfg = load(db, src)
        _create_profile(db, name, cfg["settings"], cfg["slots"], notes or f"copied from {cfg['profile']}")


def profile_use(name, actor=None):
    with DB(actor) as db:
        active(db)
        _put(db, "active_profile", {"only_row": 1, "profile_id": profile_id(db, name)})
        r = render(actor, db)
        if r["errors"]:
            raise ValueError(f"profile {name}: " + "; ".join(r["errors"]))
        return r


def profile_rename(old, new, actor=None):
    with DB(actor) as db:
        _put(db, "profile", {"id": profile_id(db, old), "name": new})
        return render(actor, db)


def profile_notes(name, notes, actor=None):
    with DB(actor) as db:
        _put(db, "profile", {"id": profile_id(db, name), "notes": notes})


def profile_delete(name, actor=None):
    with DB(actor) as db:
        pid = profile_id(db, name)
        if pid == active(db)[0]:
            raise ValueError(f"{name} is the active profile: use another one first")
        db.bulk = True  # its settings and slots go with it (ON DELETE CASCADE), logged as the one profile row
        _delete(db, "profile", {"id": pid})


def profile_export(name=None, actor=None):
    with DB(actor) as db:
        pid = profile_id(db, name) if name else active(db)[0]
        cfg = load(db, pid)
        notes = db.val("SELECT notes FROM profile WHERE id = ?", (pid,))
    return {"profile": cfg["profile"], "notes": notes, "settings": cfg["settings"],
            "slots": [{"slot": i, **s} for i, s in sorted(cfg["slots"].items())]}


def profile_import(data, name=None, actor=None):
    """A profile_export() dict as a new profile (name: data's, else NAME)."""
    name = name or data.get("profile")
    settings = {k: str(v) for k, v in (data.get("settings") or {}).items()}
    for k, v in settings.items():
        if not re.fullmatch(r"[A-Z][A-Z0-9_]*", k) or cat.is_derived(k) or cat.check_value(k, v):
            raise ValueError(f"{k}={v}: not a valid setting")
    slots = {}
    for s in data.get("slots") or []:
        i = int(s["slot"])
        if not 0 <= i < cat.MAX_SLOTS or not re.fullmatch(r"[a-z0-9]+(_[0-9]+)?", s.get("model", "")):
            raise ValueError(f"bad slot {s}")
        has_pose = all(s.get(k) is not None for k in ("x", "y", "yaw"))
        x, y, yaw = _pose(s if has_pose else None)
        slots[i] = {"model": s["model"], "x": x, "y": y, "yaw": yaw}
    with DB(actor) as db:
        _create_profile(db, name, settings, slots, data.get("notes") or "imported")
    return name


def import_env(path, profile=None, actor=None):
    """An old-style .env into a profile: a new one, or replacing the settings and slots of an existing one."""
    settings, slots, notes = import_env_vals(parse_env(Path(path).read_text()))
    with DB(actor) as db:
        active(db)
        pid = db.val("SELECT id FROM profile WHERE name = ?", (profile,)) if profile else None
        if pid is None:
            _create_profile(db, profile or Path(path).name, settings, slots, f"imported from {path}")
        else:
            for k in [r[0] for r in db.all("SELECT key FROM setting_value WHERE profile_id = ?", (pid,))]:
                if k not in settings:
                    _delete(db, "setting_value", {"profile_id": pid, "key": k})
            for i in [r[0] for r in db.all("SELECT slot FROM robot_slot WHERE profile_id = ?", (pid,))]:
                if i not in slots:
                    _delete(db, "robot_slot", {"profile_id": pid, "slot": i})
            for k, v in settings.items():
                _put(db, "setting_value", {"profile_id": pid, "key": k, "value": v})
            for i, s in slots.items():
                _put_slot(db, pid, i, s["model"], s["x"], s["y"], s["yaw"])
        render(actor, db)
    return notes


# ---------------------------------------------------------------- real robots

def real_robots(actor=None):
    """{id: {host, user, cutter}}: from the database, else the copy render() last wrote."""
    try:
        with DB(actor) as db:
            rows = _real_rows(db)
        _write_real_file(rows)
        return {r["id"]: {"host": r["host"], "user": r["user"], "cutter": r["cutter"]} for r in rows}
    except Unavailable:
        try:
            data = json.loads(REAL_FILE.read_text())
        except (OSError, ValueError):
            return {}
        return {k: {"host": v.get("host"), "user": v.get("user") or "robot", "cutter": bool(v.get("cutter"))}
                for k, v in data.items() if isinstance(v, dict)}


def real_save(rid, host, user="robot", cutter=False, actor=None):
    with DB(actor) as db:
        _put(db, "real_robot", {"id": rid, "host": host, "ssh_user": user or "robot", "cutter": int(bool(cutter))})
        _write_real_file(_real_rows(db))


def real_remove(rid, actor=None):
    with DB(actor) as db:
        linked = linked_real_robots(load(db), _real_rows(db))
        if rid in linked:  # off the list, a sim robot of that name would no longer be refused (problems())
            raise ValueError(f"the base station's router still dials {rid} ({linked[rid]}): unlink it first")
        if not _delete(db, "real_robot", {"id": rid}):
            raise ValueError(f"{rid} is not in the list")
        _write_real_file(_real_rows(db))


# ---------------------------------------------------------------- history and runs

def _slot_text(r):
    if not r:
        return "(none)"
    pose = f" at ({r['x']:g}, {r['y']:g}, {r['yaw_deg']:g}°)" if r.get("x") is not None else ""
    return r["model"] + pose


def _real_text(r):
    return f"{r['ssh_user']}@{r['host']}{', cutter' if r['cutter'] else ''}" if r else "(none)"


def describe(e, names):
    o, n = e["old_row"], e["new_row"]
    r = n or o or {}
    t = e["tbl"]
    if t == "import":
        return f"settings imported from {r.get('source')}"
    where = f"[{names.get(r.get('profile_id'), '#' + str(r.get('profile_id')))}] " if "profile_id" in r and t != "active_profile" else ""
    if t == "setting_value":
        return f"{where}{r['key']}: {o['value'] if o else '(default)'} -> {n['value'] if n else '(default)'}"
    if t == "robot_slot":
        return f"{where}slot {r['slot']}: {_slot_text(o)} -> {_slot_text(n)}"
    if t == "real_robot":
        return f"real robot {r['id']}: {_real_text(o)} -> {_real_text(n)}"
    if t == "active_profile":
        return (f"active profile: {names.get(o['profile_id'], '#' + str(o['profile_id'])) if o else '(none)'} -> "
                f"{names.get(n['profile_id'], '#' + str(n['profile_id'])) if n else '(none)'}")
    if t == "profile":
        if e["op"] == "INSERT":
            return f"profile {n['name']} created"
        if e["op"] == "DELETE":
            return f"profile {o['name']} deleted"
        return (f"profile {o['name']} renamed {n['name']}" if o["name"] != n["name"]
                else f"profile {n['name']}: notes changed")
    return f"{t} {e['op']}"


def history(limit=50, actor=None):
    with DB(actor) as db:
        rows = db.dicts("SELECT id, at, actor, tbl, op, old_row, new_row FROM change_log ORDER BY id DESC LIMIT ?",
                        (limit,))
        names = dict(db.all("SELECT id, name FROM profile"))
    for r in rows:
        r["old_row"] = json.loads(r["old_row"]) if r["old_row"] else None
        r["new_row"] = json.loads(r["new_row"]) if r["new_row"] else None
        r["text"] = describe(r, names)
        r["revertible"] = r["tbl"] in ("setting_value", "robot_slot", "real_robot", "active_profile")
    return rows


def revert(entry_id, actor=None):
    """Put back what change ENTRY_ID changed (as a new change, itself in the log)."""
    with DB(actor) as db:
        e = db.dicts("SELECT tbl, op, old_row, new_row FROM change_log WHERE id = ?", (entry_id,))
        if not e:
            raise ValueError(f"no change {entry_id}")
        t = e[0]["tbl"]
        o = json.loads(e[0]["old_row"]) if e[0]["old_row"] else None
        n = json.loads(e[0]["new_row"]) if e[0]["new_row"] else None
        if t == "active_profile":
            if not o or not db.val("SELECT 1 FROM profile WHERE id = ?", (o["profile_id"],)):
                raise ValueError("that profile no longer exists")
            _put(db, "active_profile", {"only_row": 1, "profile_id": o["profile_id"]})
        elif t in BULK_TABLES + ("real_robot",):
            r = o or n
            if "profile_id" in r and not db.val("SELECT 1 FROM profile WHERE id = ?", (r["profile_id"],)):
                raise ValueError("its profile no longer exists")
            if o is None:  # it was added: remove it
                _delete(db, t, n)
            else:
                _put(db, t, {c: o[c] for c in COLUMNS[t]})
        else:
            raise ValueError(f"a {t} change can't be reverted")
        r = render(actor, db)
        if r["errors"]:
            raise ValueError("; ".join(r["errors"]))
        return r


def run_begin(command, actor=None):
    """Record a scripts/fleet.sh run with the variables it runs with; its id, or None without a database."""
    commit = (git("rev-parse", "--short", "HEAD") or "").strip()
    if commit and (git("status", "--porcelain", "--untracked-files=no") or "").strip():
        commit += "-dirty"
    try:
        with DB(actor) as db:
            _, name = active(db)
            return db.val("INSERT INTO run (actor, command, profile, git_commit, env) VALUES (?, ?, ?, ?, ?) "
                          "RETURNING id", (actor or default_actor(), command, name, commit,
                                           json.dumps(read_env_file())))
    except Unavailable:
        return None


def run_end(run_id, code, actor=None):
    try:
        with DB(actor) as db:
            db.q("UPDATE run SET finished_at = ?, exit_code = ? WHERE id = ?", (now_iso(), code, run_id))
    except Unavailable:
        pass


def runs(limit=30, actor=None):
    with DB(actor) as db:
        rows = db.dicts("SELECT id, started_at, finished_at, actor, command, profile, git_commit, exit_code, env "
                        "FROM run ORDER BY id DESC LIMIT ?", (limit,))
    for r in rows:
        r["env"] = json.loads(r["env"]) if r["env"] else {}
    return rows


# ---------------------------------------------------------------- the web UI's view

def view(actor=None):
    """Everything the Configuration page shows, in one round trip."""
    try:
        with DB(actor) as db:
            cfg = load(db)
            r = render(actor, db)
            plist = profiles(db)
    except Unavailable as e:
        cfg = {"profile_id": None, "profile": None, "slots": {}, "settings": {}}
        env_vals = read_env_file()
        settings, slots, _ = import_env_vals(env_vals)
        cfg.update(settings=settings, slots=slots)
        r = {"source": "offline", "why": str(e), "errors": [], "warnings": []}
        plist = []
    errors, warnings = (r["errors"], r["warnings"]) if r["source"] == "database" else problems(cfg)
    try:
        db_name = str(DB_FILE.relative_to(ROOT))
    except ValueError:
        db_name = str(DB_FILE)
    return {"source": r["source"], "why": r.get("why", ""), "profile": cfg["profile"], "profiles": plist,
            "catalog": cat.SETTINGS, "sections": cat.SECTIONS, "settings": cfg["settings"],
            "num_robots": num_robots(cfg), "max_slots": cat.MAX_SLOTS,
            "slots": [dict(cfg["slots"].get(i) or {"model": GENERIC_SLOT_MODEL, "x": None, "y": None, "yaw": None},
                           slot=i, stored=i in cfg["slots"], ns=slot_ns((cfg["slots"].get(i) or {}).get(
                               "model", GENERIC_SLOT_MODEL), i)) for i in range(cat.MAX_SLOTS)],
            "errors": errors, "warnings": warnings, "db": db_name}


# ---------------------------------------------------------------- check: catalog vs. compose

def check():
    text = (ROOT / "docker-compose.yml").read_text() + (ROOT / "basestation.compose.yml").read_text()
    used = {}
    for m in re.finditer(r"\$\{([A-Z][A-Z0-9_]*)(:?-)?([^}$]*)", text):
        used.setdefault(m[1], set()).add(m[3] if m[2] else None)
    bad = 0
    for s in cat.SETTINGS:
        k = s["key"]
        if k in cat.NOT_IN_COMPOSE:
            continue
        if k not in used:
            print(f"{k}: in the catalog but not in docker-compose.yml / basestation.compose.yml")
            bad += 1
            continue
        defaults = used[k] - {None}
        if k == "BASESTATION_RMW":  # ${BASESTATION_RMW:-${FLEET_RMW...}}: empty = FLEET_RMW
            continue
        if defaults and defaults != {s["default"]}:
            print(f"{k}: catalog default {s['default']!r}, compose {sorted(defaults)}")
            bad += 1
    for k in sorted(used):
        if k not in cat.BY_KEY and not cat.is_derived(k) and k not in ("DISPLAY", "VAR"):
            print(f"{k}: used by compose, not in scripts/fleet_settings.py")
            bad += 1
    print("catalog matches compose" if not bad else f"{bad} problem(s)")
    return 1 if bad else 0


# ---------------------------------------------------------------- command line

def _fmt_time(t):
    t = from_iso(t) if isinstance(t, str) else t
    return t.astimezone().strftime("%Y-%m-%d %H:%M:%S") if t else ""


def _print_render(r):
    if r["source"] == "offline":
        print(f"[fleetcfg] {r['why']}; .env kept as it is" if not r.get("changed") else
              f"[fleetcfg] {r['why']}; .env made from the defaults", file=sys.stderr)
    for w in r.get("warnings", []):
        print(f"[fleetcfg] warning: {w}", file=sys.stderr)
    for e in r.get("errors", []):
        print(f"[fleetcfg] error: {e}", file=sys.stderr)


def cmd_show(a):
    v = view()
    if v["source"] == "offline":
        print(f"(settings database unusable: {v['why']}; showing .env)")
    print(f"profile: {v['profile']}   ({v['db']})")
    for section in v["sections"]:
        print(f"\n[{section}]")
        for s in v["catalog"]:
            if s["section"] != section:
                continue
            val = v["settings"].get(s["key"])
            if val is None and s["advanced"] and not a.all:
                continue
            print(f"  {s['key']:26} {val if val is not None else s['default']!s:24} "
                  f"{'' if val is not None else '(default)'}")
    other = sorted(k for k in v["settings"] if k not in cat.BY_KEY)
    if other:
        print("\n[Not in the catalog]")
        for k in other:
            print(f"  {k:26} {v['settings'][k]}")
    print(f"\n[Robot slots]  NUM_ROBOTS={v['num_robots']}")
    for s in v["slots"]:
        if s["stored"] or s["slot"] < v["num_robots"]:
            pose = f"({s['x']:g}, {s['y']:g}, {s['yaw']:g}°)" if s["x"] is not None else "default pose"
            print(f"  {s['slot']}  {s['model']:12} {s['ns']:12} {pose:28} "
                  f"{'' if s['slot'] < v['num_robots'] else '(not started)'}")
    for e in v["errors"]:
        print(f"error: {e}")
    for w in v["warnings"]:
        print(f"warning: {w}")
    if not a.all:
        print("\n(advanced settings at their default hidden: --all)")


def cmd_get(a):
    try:
        with DB() as db:
            cfg = load(db)
    except Unavailable:
        cfg = dict(default_cfg(), settings=read_env_file())
    v = effective(cfg, a.key)
    if v is None:
        return 1
    print(v)


def cmd_set(a):
    updates = {}
    for kv in a.pairs:
        if "=" not in kv:
            raise ValueError(f"{kv}: KEY=VALUE")
        k, v = kv.split("=", 1)
        updates[k.strip()] = v
    _print_render(set_settings(updates))


def cmd_unset(a):
    _print_render(set_settings({k: None for k in a.keys}))


def cmd_robots(a):
    _print_render(set_settings({"NUM_ROBOTS": str(a.n)}))


def cmd_slot(a):
    pose = None
    if a.pose:
        try:
            x, y, yaw = (float(v) for v in a.pose.split(","))
        except ValueError:
            raise ValueError("--pose X,Y,YAW (m, m, degrees)") from None
        pose = {"x": x, "y": y, "yaw": yaw}
    _print_render(set_slot(a.slot, a.model, pose, a.no_pose, a.remove))


def cmd_render(a):
    r = render()
    _print_render(r)
    if not a.quiet and r["source"] == "database":
        print(f"[fleetcfg] .env {'written' if r['changed'] else 'unchanged'} (profile {r['profile']})", file=sys.stderr)
    return 1 if r["errors"] else 0


def cmd_profile(a):
    if a.op == "list":
        with DB() as db:
            active(db)
            for p in profiles(db):
                print(f"{'*' if p['active'] else ' '} {p['name']:24} {p['num_robots'] or '-':>3} robots  "
                      f"{p['settings']:>3} settings  {p['notes']}")
    elif a.op == "use":
        _print_render(profile_use(a.args[0]))
    elif a.op == "new":
        profile_new(a.args[0], a.source)
    elif a.op == "rename":
        profile_rename(a.args[0], a.args[1])
    elif a.op == "delete":
        profile_delete(a.args[0])
    elif a.op == "notes":
        profile_notes(a.args[0], " ".join(a.args[1:]))
    elif a.op == "export":
        print(json.dumps(profile_export(a.args[0] if a.args else None), indent=2))
    elif a.op == "import":
        print(f"imported as profile {profile_import(json.loads(Path(a.args[0]).read_text()), a.name)}")


def cmd_history(a):
    for r in reversed(history(a.n)):
        print(f"{r['id']:>6}  {_fmt_time(r['at'])}  {r['actor']:24}  {r['text']}")


def cmd_revert(a):
    _print_render(revert(a.id))


def cmd_runs(a):
    for r in reversed(runs(a.n)):
        code = "running" if r["exit_code"] is None and not r["finished_at"] else f"exit {r['exit_code']}"
        print(f"{r['id']:>5}  {_fmt_time(r['started_at'])}  {code:8}  {r['command']:24} profile {r['profile']}, "
              f"{r['env'].get('NUM_ROBOTS', '?')} robot(s), git {r['git_commit']}  ({r['actor']})")


def cmd_real(a):
    if a.op == "list":
        for rid, c in real_robots().items():
            print(f"{rid:12} {c['user']}@{c['host']}{'  cutter' if c['cutter'] else ''}")
    elif a.op == "set":
        cur = real_robots().get(a.id, {})
        real_save(a.id, a.host or cur.get("host") or f"cpr-{a.id.replace('_', '-')}.local",
                  a.user or cur.get("user") or "robot", cur.get("cutter", False) if a.cutter is None else a.cutter)
    elif a.op == "remove":
        real_remove(a.id)


def cmd_import_env(a):
    for n in import_env(a.file, a.profile):
        print(f"note: {n}")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("show")
    p.add_argument("--all", action="store_true", help="also advanced settings left at their default")
    p.set_defaults(fn=cmd_show)
    p = sub.add_parser("get")
    p.add_argument("key")
    p.set_defaults(fn=cmd_get)
    p = sub.add_parser("set")
    p.add_argument("pairs", nargs="+", metavar="KEY=VALUE")
    p.set_defaults(fn=cmd_set)
    p = sub.add_parser("unset")
    p.add_argument("keys", nargs="+")
    p.set_defaults(fn=cmd_unset)
    p = sub.add_parser("robots")
    p.add_argument("n", type=int)
    p.set_defaults(fn=cmd_robots)
    p = sub.add_parser("slot")
    p.add_argument("slot", type=int)
    p.add_argument("model", nargs="?")
    p.add_argument("--pose", help="X,Y,YAW: metres, metres, degrees")
    p.add_argument("--no-pose", action="store_true", help="the sim's default layout")
    p.add_argument("--remove", action="store_true", help="forget the slot (a300 if it is started)")
    p.set_defaults(fn=cmd_slot)
    p = sub.add_parser("render")
    p.add_argument("--quiet", action="store_true")
    p.set_defaults(fn=cmd_render)
    p = sub.add_parser("profile")
    p.add_argument("op", choices=["list", "use", "new", "rename", "delete", "notes", "export", "import"])
    p.add_argument("args", nargs="*")
    p.add_argument("--from", dest="source", help="new: copy this profile (default: the active one)")
    p.add_argument("--name", help="import: the new profile's name")
    p.set_defaults(fn=cmd_profile)
    p = sub.add_parser("history")
    p.add_argument("-n", type=int, default=30)
    p.set_defaults(fn=cmd_history)
    p = sub.add_parser("revert")
    p.add_argument("id", type=int)
    p.set_defaults(fn=cmd_revert)
    p = sub.add_parser("runs")
    p.add_argument("-n", type=int, default=20)
    p.set_defaults(fn=cmd_runs)
    p = sub.add_parser("real")
    p.add_argument("op", choices=["list", "set", "remove"])
    p.add_argument("id", nargs="?")
    p.add_argument("--host")
    p.add_argument("--user")
    p.add_argument("--cutter", action="store_true", default=None)
    p.add_argument("--no-cutter", dest="cutter", action="store_false")
    p.set_defaults(fn=cmd_real)
    p = sub.add_parser("import-env")
    p.add_argument("file")
    p.add_argument("--profile")
    p.set_defaults(fn=cmd_import_env)
    p = sub.add_parser("check")
    p.set_defaults(fn=lambda a: check())
    # used by scripts/fleet.sh
    p = sub.add_parser("run-begin")
    p.add_argument("command")
    p.set_defaults(fn=lambda a: print(run_begin(a.command) or ""))
    p = sub.add_parser("run-end")
    p.add_argument("id", type=int)
    p.add_argument("code", type=int)
    p.set_defaults(fn=lambda a: run_end(a.id, a.code))
    a = ap.parse_args()
    if a.cmd == "real" and a.op != "list" and not a.id:
        ap.error("real set/remove need an ID")
    try:
        sys.exit(a.fn(a) or 0)
    except (ValueError, Unavailable) as e:
        print(f"fleetcfg: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
