#!/usr/bin/env python3
"""The fleet's settings, kept in the base station's fleet_config database; .env is generated from them.

  scripts/fleetcfg.py show                          the active profile: settings, robot slots, problems
  scripts/fleetcfg.py get KEY                       a setting's value (its default if the profile doesn't set it)
  scripts/fleetcfg.py set KEY=VALUE ...             change settings (and render .env); `unset KEY ...` = default
  scripts/fleetcfg.py robots N                      NUM_ROBOTS
  scripts/fleetcfg.py slot I MODEL [--pose X,Y,YAW | --no-pose]   slot I's model and spawn pose; `slot I --remove`
  scripts/fleetcfg.py render                        write .env (and the real-robot list) from the database
  scripts/fleetcfg.py profile list | use NAME | new NAME [--from P] | rename OLD NEW | delete NAME
                              | notes NAME TEXT | export [NAME] | import FILE [--name NAME]
  scripts/fleetcfg.py history [-n N] | revert ID    the change log (who changed what, when); undo one change
  scripts/fleetcfg.py runs [-n N]                   sim starts and spawns (scripts/fleet.sh) and what they ran with
  scripts/fleetcfg.py real list | set ID [--host H] [--user U] [--cutter | --no-cutter] | remove ID
  scripts/fleetcfg.py import-env FILE [--profile NAME]   load an old-style .env into a profile
  scripts/fleetcfg.py init                          create the database in a running base station (normally
                                                    basestation/entrypoint.sh does it at start)
  scripts/fleetcfg.py check                         the catalog's defaults vs. docker-compose.yml's

What each setting means is scripts/fleet_settings.py. The database is reached like status_server does: the base
station's PostgreSQL on 127.0.0.1:5433 (BASESTATION_PG_PORT), user admin, PGPASSWORD from db.env; FLEET_DB_HOST /
FLEET_DB_PORT / FLEET_DB_USER / FLEET_CONFIG_DB override. If it can't be reached, .env stays as last rendered (the
fleet still starts) and only changes are refused. The first use imports the existing .env (or the last one
committed to git) and tools/sim_ui/real_robots.json into a profile "default".
Needs psycopg (3) or psycopg2; tools/sim_ui/server.py imports this module.
"""
import argparse
import getpass
import json
import math
import os
import re
import socket
import subprocess
import sys
import tempfile
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import fleet_settings as cat  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
ENV_FILE = ROOT / ".env"
# The real-robot list as last read from the database: what the web UI uses while the database is down.
REAL_FILE = ROOT / "tools/sim_ui/real_robots.json"
HEADER = "# GENERATED by scripts/fleetcfg.py"
DB_NAME = os.environ.get("FLEET_CONFIG_DB", "fleet_config")
BASESTATION = "basestation"
FIRST_USE_LOCK = 740633  # pg_advisory_xact_lock key: one first-use import at a time
OFFLINE_RETRY_S = 10  # after a failed connection, callers in this process get Unavailable at once for this long
GENERIC_SLOT_MODEL = "a300"  # a slot with no row (docker-compose.yml's ${ROBOT_MODEL_<i>:-a300})


class Unavailable(RuntimeError):
    """The database can't be reached (or has no tables yet)."""


def default_actor():
    return f"{getpass.getuser()}@{socket.gethostname()}"


# ---------------------------------------------------------------- .env files

def parse_env(text):
    """KEY=VALUE lines as docker compose reads them (last one wins; surrounding quotes removed)."""
    out = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        k, v = k.strip().removeprefix("export ").strip(), v.strip()
        if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":
            v = v[1:-1]
        out[k] = v
    return out


def read_env_file(path=ENV_FILE):
    try:
        return parse_env(path.read_text())
    except OSError:
        return {}


def env_is_generated(path=ENV_FILE):
    try:
        with open(path) as f:
            return f.readline().startswith(HEADER)
    except OSError:
        return False


def write_if_changed(path, text):
    try:
        if path.read_text() == text:
            return False
    except OSError:
        pass
    # a unique temporary file: the web UI renders from several threads at once
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name.lstrip('.')}.", suffix=".tmp")
    with os.fdopen(fd, "w") as f:
        f.write(text)
    os.chmod(tmp, 0o644)
    os.replace(tmp, path)  # atomic: compose never reads half a file
    return True


def git(*args):
    p = subprocess.run(["git", "-C", str(ROOT), *args], capture_output=True, text=True)
    return p.stdout if p.returncode == 0 else None


def from_git_history(rel):
    """A file's last committed content (before it was untracked), for the first-use import on a fresh checkout."""
    commit = (git("log", "-1", "--format=%H", "--", rel) or "").strip()
    if not commit:
        return None, None
    for rev in (commit, commit + "^"):  # the commit that untracked it has it only in its parent
        text = git("show", f"{rev}:{rel}")
        if text is not None:
            return text, f"git {rev[:9]}"
    return None, None


# ---------------------------------------------------------------- database

_down = {"until": 0.0, "why": ""}


def _driver():
    try:
        import psycopg
        return psycopg
    except ImportError:
        pass
    try:
        import psycopg2
        return psycopg2
    except ImportError:
        raise Unavailable("no PostgreSQL driver for python3: pip install 'psycopg[binary]' "
                          "(or sudo apt install python3-psycopg2)") from None


def conn_params():
    env = read_env_file()
    secrets = read_env_file(ROOT / "db.env")
    return {"host": os.environ.get("FLEET_DB_HOST", "127.0.0.1"),
            "port": int(os.environ.get("FLEET_DB_PORT") or env.get("BASESTATION_PG_PORT") or 5433),
            "user": os.environ.get("FLEET_DB_USER") or env.get("BASESTATION_PG_USER") or "admin",
            "password": secrets.get("PGPASSWORD") or os.environ.get("PGPASSWORD", ""),
            "dbname": DB_NAME, "connect_timeout": 3}


def basestation_running():
    p = subprocess.run(["docker", "inspect", "-f", "{{.State.Running}}", BASESTATION], capture_output=True, text=True)
    return p.stdout.strip() == "true"


CONSTRAINTS = {  # basestation/config_migrations/: what a violation means
    "profile_name_key": "there is a profile with that name already",
    "profile_name_check": "a profile name is letters, digits, spaces, '.', '_' and '-' (up to 63)",
    "real_robot_id_check": "a real robot id looks like j100_0921",
    "robot_slot_model_check": "a model id looks like a300 or j100_0921",
}


class DB:
    """One connection, one transaction: `with DB() as db:` commits at the end, rolls back on an exception."""

    def __init__(self, actor=None, auto_init=True):
        if time.time() < _down["until"]:
            raise Unavailable(_down["why"])
        drv = _driver()
        params = conn_params()
        try:
            self.conn = drv.connect(**params)
        except drv.Error as e:
            msg = str(e).strip().splitlines()[0] if str(e).strip() else type(e).__name__
            # a base station from before fleet_config existed: create it in place (no restart needed)
            if auto_init and "does not exist" in msg and basestation_running() and init(quiet=True) == 0:
                self.__init__(actor, auto_init=False)
                return
            why = (f"no settings database at {params['host']}:{params['port']}/{DB_NAME} ({msg}); is the base "
                   "station running? docker compose -f basestation.compose.yml up -d")
            _down.update(until=time.time() + OFFLINE_RETRY_S, why=why)
            raise Unavailable(why) from None
        self.drv = drv
        self.cur = self.conn.cursor()
        if self.val("SELECT to_regclass('profile') IS NULL"):
            self.conn.close()
            if auto_init and basestation_running() and init(quiet=True) == 0:
                self.__init__(actor, auto_init=False)
                return
            raise Unavailable(f"{DB_NAME} has no tables: scripts/fleetcfg.py init")
        self.q("SELECT set_config('fleet.actor', %s, false)", (actor or default_actor(),))

    def q(self, sql, args=()):
        self.cur.execute(sql, args)
        return self.cur

    def all(self, sql, args=()):
        return self.q(sql, args).fetchall()

    def one(self, sql, args=()):
        return self.q(sql, args).fetchone()

    def val(self, sql, args=()):
        row = self.one(sql, args)
        return row[0] if row else None

    def dicts(self, sql, args=()):
        cur = self.q(sql, args)
        cols = [d[0] for d in cur.description]
        return [dict(zip(cols, r)) for r in cur.fetchall()]

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        try:
            if exc_type is None:
                self.conn.commit()
            else:
                self.conn.rollback()
        finally:
            self.conn.close()
        if isinstance(exc, self.drv.Error):  # a constraint (name taken, bad model id...): the caller's mistake
            msg = str(exc).strip().splitlines()[0]
            for constraint, text in CONSTRAINTS.items():
                if constraint in msg:
                    msg = text
            raise ValueError(msg) from exc


def init(quiet=False):
    """Create fleet_config in the running base station container and apply basestation/config_migrations/ with
    its own migrate.sh (copied in: a container from before them doesn't mount the folder)."""
    def run(argv, **kw):
        p = subprocess.run(argv, capture_output=True, text=True, **kw)
        if p.returncode != 0 and not quiet:
            print(p.stdout + p.stderr, file=sys.stderr, end="")
        return p
    if not basestation_running():
        if not quiet:
            print("the base station is not running: docker compose -f basestation.compose.yml up -d", file=sys.stderr)
        return 1
    exists = run(["docker", "exec", BASESTATION, "psql", "-tAq", "-d", "postgres", "-c",
                  f"SELECT 1 FROM pg_database WHERE datname = '{DB_NAME}'"])
    if exists.returncode != 0:
        return 1
    if not exists.stdout.strip():
        if run(["docker", "exec", BASESTATION, "psql", "-q", "-d", "postgres", "-c",
                f'CREATE DATABASE "{DB_NAME}"']).returncode != 0:
            return 1
    # tar through docker exec, not docker cp: that fails on the container's /tmp/.docker.xauth bind mount
    tmp = "/var/tmp/fleetcfg_migrations"
    src = ROOT / "basestation/config_migrations"
    tar = subprocess.run(["tar", "-C", str(src), "-c", "."], capture_output=True)
    if run(["docker", "exec", "-i", BASESTATION, "sh", "-c", f'rm -rf {tmp} && mkdir -p {tmp} && tar -C {tmp} -x'],
           input=tar.stdout.decode("latin-1"), encoding="latin-1").returncode != 0:
        return 1
    p = run(["docker", "exec", "-e", f"PGDATABASE={DB_NAME}", BASESTATION, "/basestation-migrate.sh", tmp])
    if not quiet and p.returncode == 0:
        print(p.stdout, end="")
    return p.returncode


# ---------------------------------------------------------------- the active profile

def slot_ns(model, slot):
    """Container name / ROS namespace: a real robot's own id, else <model>_<slot %04d> (docker-compose.yml)."""
    return model if "_" in model else f"{model}_{slot:04d}"


def import_env_vals(vals):
    """An old-style .env's variables -> (settings, slots, notes). Derived variables are dropped (render makes them)."""
    settings, slots, notes = {}, {}, []
    for k, v in vals.items():
        m = re.fullmatch(r"ROBOT_(MODEL|POSE)_(\d+)", k)
        if m:
            i = int(m[2])
            if i >= cat.MAX_SLOTS:
                notes.append(f"{k}: no slot {i} (0-{cat.MAX_SLOTS - 1})")
                continue
            s = slots.setdefault(i, {"model": GENERIC_SLOT_MODEL, "x": None, "y": None, "yaw": None})
            if m[1] == "MODEL":
                if not re.fullmatch(r"[a-z0-9]+(_[0-9]+)?", v):
                    notes.append(f"{k}={v}: not a model id, slot {i} left {s['model']}")
                else:
                    s["model"] = v
            else:
                try:
                    x, y, yaw = (float(p) for p in v.split(","))
                    s.update(x=x, y=y, yaw=yaw)
                except ValueError:
                    notes.append(f"{k}={v}: not x,y,yaw")
            continue
        if cat.is_derived(k):
            continue
        if not re.fullmatch(r"[A-Z][A-Z0-9_]*", k):
            notes.append(f"{k}: not a setting name, skipped")
            continue
        err = cat.check_value(k, v)
        if err:
            notes.append(f"{k}={v}: skipped, must be {err}")
            continue
        settings[k] = v
    return settings, slots, notes


def _bulk(db):
    """The change log records only the profile row for the rest of this transaction (fleet.bulk, log_change)."""
    db.q("SELECT set_config('fleet.bulk', 'on', true)")


def _create_profile(db, name, settings, slots, notes=""):
    _bulk(db)
    pid = db.val("INSERT INTO profile (name, notes) VALUES (%s, %s) RETURNING id", (name, notes))
    for k, v in settings.items():
        db.q("INSERT INTO setting_value (profile_id, key, value) VALUES (%s, %s, %s)", (pid, k, v))
    for i, s in slots.items():
        db.q("INSERT INTO robot_slot (profile_id, slot, model, x, y, yaw_deg) VALUES (%s, %s, %s, %s, %s, %s)",
             (pid, i, s["model"], s.get("x"), s.get("y"), s.get("yaw")))
    return pid


def _first_use(db):
    """No profile yet: import this checkout's .env (hand-written from before the database, or generated by an
    earlier one: the newest state either way), else the last one committed to git, and real_robots.json."""
    notes = []
    if ENV_FILE.exists():
        text, source = ENV_FILE.read_text(), "the .env file"
    else:
        text, source = from_git_history(".env")
    if text is None:
        settings, slots, source = {}, {}, "defaults"
    else:
        settings, slots, notes = import_env_vals(parse_env(text))
    pid = _create_profile(db, "default", settings, slots, f"imported from {source}")
    db.q("INSERT INTO active_profile (profile_id) VALUES (%s)", (pid,))
    if not db.val("SELECT count(*) FROM real_robot"):
        try:
            real = json.loads(REAL_FILE.read_text())
        except (OSError, ValueError):
            text, _ = from_git_history(str(REAL_FILE.relative_to(ROOT)))
            real = json.loads(text) if text else {}
        for rid, c in real.items():
            if re.fullmatch(r"[a-z0-9]+_[0-9]+", rid) and isinstance(c, dict):
                db.q("INSERT INTO real_robot (id, host, ssh_user, cutter) VALUES (%s, %s, %s, %s)",
                     (rid, c.get("host") or f"cpr-{rid.replace('_', '-')}.local", c.get("user") or "robot",
                      bool(c.get("cutter"))))
    for n in notes:
        print(f"[fleetcfg] import: {n}", file=sys.stderr)
    print(f"[fleetcfg] first use: profile 'default' imported from {source}", file=sys.stderr)


def active(db):
    """(id, name) of the active profile; the first use of the database imports one."""
    row = db.one("SELECT p.id, p.name FROM active_profile a JOIN profile p ON p.id = a.profile_id")
    if row:
        return row
    db.q("SELECT pg_advisory_xact_lock(%s)", (FIRST_USE_LOCK,))
    row = db.one("SELECT p.id, p.name FROM active_profile a JOIN profile p ON p.id = a.profile_id")
    if row:
        return row
    first = db.one("SELECT id, name FROM profile ORDER BY id LIMIT 1")
    if first:
        db.q("INSERT INTO active_profile (profile_id) VALUES (%s)", (first[0],))
        return first
    _first_use(db)
    return db.one("SELECT p.id, p.name FROM active_profile a JOIN profile p ON p.id = a.profile_id")


def profile_id(db, name):
    pid = db.val("SELECT id FROM profile WHERE name = %s", (name,))
    if pid is None:
        raise ValueError(f"no profile {name!r}")
    return pid


def load(db, pid=None):
    """{profile, settings: {key: value}, slots: {i: {model, x, y, yaw}}} of a profile (the active one by default)."""
    if pid is None:
        pid, name = active(db)
    else:
        name = db.val("SELECT name FROM profile WHERE id = %s", (pid,))
    settings = dict(db.all("SELECT key, value FROM setting_value WHERE profile_id = %s ORDER BY key", (pid,)))
    slots = {r[0]: {"model": r[1], "x": r[2], "y": r[3], "yaw": r[4]} for r in
             db.all("SELECT slot, model, x, y, yaw_deg FROM robot_slot WHERE profile_id = %s ORDER BY slot", (pid,))}
    return {"profile_id": pid, "profile": name, "settings": settings, "slots": slots}


def default_cfg():
    return {"profile_id": None, "profile": None, "settings": {}, "slots": {}}


def effective(cfg, key):
    v = cfg["settings"].get(key)
    if v is None and key in cat.BY_KEY:
        v = cat.BY_KEY[key]["default"]
    return v


def num_robots(cfg):
    try:
        return int(effective(cfg, "NUM_ROBOTS") or 0)
    except ValueError:
        return 0


def problems(cfg):
    """(errors, warnings): errors stop render (compose would fail or the sim reject the spawn)."""
    errors, warnings = [], []
    n = num_robots(cfg)
    if not 0 <= n <= cat.MAX_SLOTS:
        errors.append(f"NUM_ROBOTS={n}: 0-{cat.MAX_SLOTS}")
        n = 0
    seen = {}
    for i in range(n):
        model = cfg["slots"].get(i, {}).get("model", GENERIC_SLOT_MODEL)
        ns = slot_ns(model, i)
        if ns in seen:
            errors.append(f"slots {seen[ns]} and {i} are both {ns}: one real robot can only be in one slot")
        seen[ns] = i
        if "_" in model and not (ROOT / "robot_data" / model / "robot.yaml").exists():
            warnings.append(f"slot {i} ({model}): no robot_data/{model}/robot.yaml, its container exits at once")
        if not (ROOT / "sim/assets" / model / f"{model}.urdf").exists():
            warnings.append(f"slot {i}: no sim model sim/assets/{model}/ (scripts/gen_urdf.sh)")
    for k, v in cfg["settings"].items():
        err = cat.check_value(k, v)
        if err:
            errors.append(f"{k}={v}: must be {err}")
    return errors, warnings


def _env_value(v):
    return f'"{v}"' if re.search(r"[\s#]", v) else v


def render_text(cfg, source):
    """The .env text for a profile: its settings (unset ones are left to compose's defaults) and the slots.
    No timestamp: the same settings give the same text, so .env is only rewritten when they change."""
    lines = [f"{HEADER} from {source} -- do not edit: changes are overwritten.",
             "# Change settings in the web UI (tools/sim_ui, Configuration) or with scripts/fleetcfg.py set KEY=VALUE.",
             f"# Profile: {cfg['profile'] or '(none: database unreachable, defaults)'}."]
    settings = dict(cfg["settings"])
    settings.setdefault("NUM_ROBOTS", cat.BY_KEY["NUM_ROBOTS"]["default"])
    for section in cat.SECTIONS:
        keys = [s["key"] for s in cat.SETTINGS if s["section"] == section and s["key"] in settings]
        if keys:
            lines += ["", f"# {section}"] + [f"{k}={_env_value(settings[k])}" for k in keys]
    other = sorted(k for k in settings if k not in cat.BY_KEY)
    if other:
        lines += ["", "# Not in scripts/fleet_settings.py"] + [f"{k}={_env_value(settings[k])}" for k in other]
    n = num_robots(cfg)
    lines += ["", "# Robot slots: compose profile n<NUM_ROBOTS> starts slots 0..N-1; container name, hostname",
              "# and namespace follow each slot's model (see docker-compose.yml)", f"COMPOSE_PROFILES=n{n}"]
    for i in range(cat.MAX_SLOTS):
        s = cfg["slots"].get(i)
        model = s["model"] if s else GENERIC_SLOT_MODEL
        if s:
            lines.append(f"ROBOT_MODEL_{i}={model}")
            if s.get("x") is not None:
                lines.append(f"ROBOT_POSE_{i}={s['x']:g},{s['y']:g},{s['yaw']:g}")
        if "_" in model:
            lines.append(f"ROBOT_SUFFIX_{i}=")
        lines.append(f"ROBOT_HOSTNAME_{i}=cpr-{slot_ns(model, i).replace('_', '-')}")
    return "\n".join(lines) + "\n"


def _real_rows(db):
    return db.dicts("SELECT id, host, ssh_user AS user, cutter FROM real_robot ORDER BY id")


def _write_real_file(rows):
    data = {r["id"]: {"host": r["host"], **({"user": r["user"]} if r["user"] != "robot" else {}),
                      "cutter": r["cutter"]} for r in rows}
    write_if_changed(REAL_FILE, json.dumps(data, indent=2) + "\n")


def render(actor=None, db=None):
    """Write .env (and the offline real-robot list) from the active profile. Returns {source, profile, changed,
    errors, warnings, why}: source "database", or "offline" (database unreachable: .env kept, or made from the
    defaults if there is none). Errors: nothing written."""
    try:
        if db is None:
            with DB(actor) as own:
                return render(actor, own)
        cfg = load(db)
        real = _real_rows(db)
    except Unavailable as e:
        r = {"source": "offline", "why": str(e), "profile": None, "errors": [], "warnings": [], "changed": False}
        if not ENV_FILE.exists():
            r["changed"] = write_if_changed(ENV_FILE, render_text(default_cfg(), "the defaults (no database)"))
        return r
    errors, warnings = problems(cfg)
    r = {"source": "database", "why": "", "profile": cfg["profile"], "errors": errors, "warnings": warnings,
         "changed": False}
    if not errors:
        r["changed"] = write_if_changed(ENV_FILE, render_text(cfg, f"database {DB_NAME}"))
        _write_real_file(real)
    return r


LAST_RENDER = {}  # env()'s last render(): where .env came from (the web UI's header shows it)


def env(actor=None):
    """The variables compose sees: .env rendered fresh from the database when it is reachable, else as it is."""
    global LAST_RENDER
    LAST_RENDER = render(actor)  # rebound, not updated in place: other threads read it
    return read_env_file()


# ---------------------------------------------------------------- changes

def set_settings(updates, actor=None):
    """{key: value or None (= back to the default)} into the active profile, then render. Values already in effect
    are skipped, so a caller that rewrites unchanged values works while the database is down."""
    for k, v in updates.items():
        if not re.fullmatch(r"[A-Z][A-Z0-9_]*", k) or cat.is_derived(k):
            raise ValueError(f"{k}: not a setting (robot slots: scripts/fleetcfg.py slot / robots)")
        if v is not None:
            err = cat.check_value(k, str(v))
            if err:
                raise ValueError(f"{k} must be {err}")
    current = read_env_file()
    unchanged = all(v is not None and (current[k] if k in current else cat.BY_KEY.get(k, {}).get("default")) == str(v)
                    for k, v in updates.items())
    try:
        with DB(actor) as db:
            pid, _ = active(db)
            for k, v in updates.items():
                if v is None:
                    db.q("DELETE FROM setting_value WHERE profile_id = %s AND key = %s", (pid, k))
                else:
                    db.q("INSERT INTO setting_value (profile_id, key, value) VALUES (%s, %s, %s) ON CONFLICT "
                         "(profile_id, key) DO UPDATE SET value = EXCLUDED.value", (pid, k, str(v)))
            r = render(actor, db)
            if r["errors"]:
                raise ValueError("; ".join(r["errors"]))
            return r
    except Unavailable as e:
        if unchanged:  # nothing to change: .env already says so
            return {"source": "offline", "why": str(e), "changed": False, "errors": [], "warnings": []}
        raise


def _pose(p):
    if p is None:
        return None, None, None
    vals = [float(p.get(k)) for k in ("x", "y", "yaw")]
    if not all(math.isfinite(v) for v in vals):
        raise ValueError("pose values must be finite numbers")
    return tuple(vals)


def set_slots(robots, actor=None, num_robots=None):
    """Slots 0..len-1 from [{model, x?, y?, yaw?} or None (= forget the slot)], a pose with all three or none;
    rows of higher slots are kept. NUM_ROBOTS too if given. Then render. While the database can't be reached, a
    request that changes no model and no NUM_ROBOTS passes (a spawn hands its poses to the sim itself)."""
    if len(robots) > cat.MAX_SLOTS:
        raise ValueError(f"at most {cat.MAX_SLOTS} robots")
    if num_robots is not None and not 0 <= int(num_robots) <= cat.MAX_SLOTS:
        raise ValueError(f"NUM_ROBOTS 0-{cat.MAX_SLOTS}")
    rows = []
    for i, r in enumerate(robots):
        if r is None:
            rows.append(None)
            continue
        model = r.get("model") or GENERIC_SLOT_MODEL
        if not re.fullmatch(r"[a-z0-9]+(_[0-9]+)?", model):
            raise ValueError(f"slot {i}: {model!r} is not a model id")
        has_pose = all(r.get(k) not in (None, "") for k in ("x", "y", "yaw"))
        rows.append((model, *_pose(r if has_pose else None)))
    current = read_env_file()
    unchanged = (num_robots is None or current.get("NUM_ROBOTS") == str(num_robots)) and all(
        row is not None and current.get(f"ROBOT_MODEL_{i}") == row[0] for i, row in enumerate(rows))
    try:
        with DB(actor) as db:
            pid, _ = active(db)
            for i, row in enumerate(rows):
                if row is None:
                    db.q("DELETE FROM robot_slot WHERE profile_id = %s AND slot = %s", (pid, i))
                    continue
                db.q("INSERT INTO robot_slot (profile_id, slot, model, x, y, yaw_deg) VALUES (%s, %s, %s, %s, %s, "
                     "%s) ON CONFLICT (profile_id, slot) DO UPDATE SET model = EXCLUDED.model, x = EXCLUDED.x, "
                     "y = EXCLUDED.y, yaw_deg = EXCLUDED.yaw_deg", (pid, i, *row))
            if num_robots is not None:
                db.q("INSERT INTO setting_value (profile_id, key, value) VALUES (%s, 'NUM_ROBOTS', %s) ON CONFLICT "
                     "(profile_id, key) DO UPDATE SET value = EXCLUDED.value", (pid, str(int(num_robots))))
            r = render(actor, db)
            if r["errors"]:
                raise ValueError("; ".join(r["errors"]))
            return r
    except Unavailable as e:
        if unchanged:
            return {"source": "offline", "why": str(e), "changed": False, "errors": [], "warnings": []}
        raise


def set_slot(i, model=None, pose=None, clear_pose=False, remove=False, actor=None):
    if not 0 <= i < cat.MAX_SLOTS:
        raise ValueError(f"slot 0-{cat.MAX_SLOTS - 1}")
    with DB(actor) as db:
        pid, _ = active(db)
        if remove:
            db.q("DELETE FROM robot_slot WHERE profile_id = %s AND slot = %s", (pid, i))
        else:
            cur = load(db, pid)["slots"].get(i, {"model": GENERIC_SLOT_MODEL, "x": None, "y": None, "yaw": None})
            model = model or cur["model"]
            if not re.fullmatch(r"[a-z0-9]+(_[0-9]+)?", model):
                raise ValueError(f"{model!r} is not a model id")
            x, y, yaw = (None, None, None) if clear_pose else _pose(pose) if pose else (cur["x"], cur["y"], cur["yaw"])
            db.q("INSERT INTO robot_slot (profile_id, slot, model, x, y, yaw_deg) VALUES (%s, %s, %s, %s, %s, %s) "
                 "ON CONFLICT (profile_id, slot) DO UPDATE SET model = EXCLUDED.model, x = EXCLUDED.x, "
                 "y = EXCLUDED.y, yaw_deg = EXCLUDED.yaw_deg", (pid, i, model, x, y, yaw))
        r = render(actor, db)
        if r["errors"]:
            raise ValueError("; ".join(r["errors"]))
        return r


# ---------------------------------------------------------------- profiles

def profiles(db):
    return db.dicts(
        "SELECT p.id, p.name, p.notes, p.created_at, (a.profile_id IS NOT NULL) AS active, "
        "(SELECT count(*) FROM setting_value s WHERE s.profile_id = p.id) AS settings, "
        "(SELECT value FROM setting_value s WHERE s.profile_id = p.id AND key = 'NUM_ROBOTS') AS num_robots "
        "FROM profile p LEFT JOIN active_profile a ON a.profile_id = p.id ORDER BY p.name")


def profile_new(name, from_name=None, notes="", actor=None):
    with DB(actor) as db:
        src = profile_id(db, from_name) if from_name else active(db)[0]
        cfg = load(db, src)
        _create_profile(db, name, cfg["settings"], cfg["slots"], notes or f"copied from {cfg['profile']}")


def profile_use(name, actor=None):
    with DB(actor) as db:
        active(db)
        pid = profile_id(db, name)
        db.q("UPDATE active_profile SET profile_id = %s", (pid,))
        r = render(actor, db)
        if r["errors"]:
            raise ValueError(f"profile {name}: " + "; ".join(r["errors"]))
        return r


def profile_rename(old, new, actor=None):
    with DB(actor) as db:
        db.q("UPDATE profile SET name = %s WHERE id = %s", (new, profile_id(db, old)))
        return render(actor, db)


def profile_notes(name, notes, actor=None):
    with DB(actor) as db:
        db.q("UPDATE profile SET notes = %s WHERE id = %s", (notes, profile_id(db, name)))


def profile_delete(name, actor=None):
    with DB(actor) as db:
        pid = profile_id(db, name)
        if pid == active(db)[0]:
            raise ValueError(f"{name} is the active profile: use another one first")
        _bulk(db)
        db.q("DELETE FROM profile WHERE id = %s", (pid,))


def profile_export(name=None, actor=None):
    with DB(actor) as db:
        pid = profile_id(db, name) if name else active(db)[0]
        cfg = load(db, pid)
        notes = db.val("SELECT notes FROM profile WHERE id = %s", (pid,))
    return {"profile": cfg["profile"], "notes": notes, "settings": cfg["settings"],
            "slots": [{"slot": i, **s} for i, s in sorted(cfg["slots"].items())]}


def profile_import(data, name=None, actor=None):
    """A profile_export() dict as a new profile (name: data's, else NAME)."""
    name = name or data.get("profile")
    settings = {k: str(v) for k, v in (data.get("settings") or {}).items()}
    for k, v in settings.items():
        if not re.fullmatch(r"[A-Z][A-Z0-9_]*", k) or cat.is_derived(k) or cat.check_value(k, v):
            raise ValueError(f"{k}={v}: not a valid setting")
    slots = {}
    for s in data.get("slots") or []:
        i = int(s["slot"])
        if not 0 <= i < cat.MAX_SLOTS or not re.fullmatch(r"[a-z0-9]+(_[0-9]+)?", s.get("model", "")):
            raise ValueError(f"bad slot {s}")
        has_pose = all(s.get(k) is not None for k in ("x", "y", "yaw"))
        x, y, yaw = _pose(s if has_pose else None)
        slots[i] = {"model": s["model"], "x": x, "y": y, "yaw": yaw}
    with DB(actor) as db:
        _create_profile(db, name, settings, slots, data.get("notes") or "imported")
    return name


def import_env(path, profile=None, actor=None):
    """An old-style .env into a profile: a new one, or replacing the settings and slots of an existing one."""
    settings, slots, notes = import_env_vals(parse_env(Path(path).read_text()))
    with DB(actor) as db:
        active(db)
        pid = db.val("SELECT id FROM profile WHERE name = %s", (profile,)) if profile else None
        if pid is None:
            _create_profile(db, profile or Path(path).name, settings, slots, f"imported from {path}")
        else:
            db.q("DELETE FROM setting_value WHERE profile_id = %s", (pid,))
            db.q("DELETE FROM robot_slot WHERE profile_id = %s", (pid,))
            for k, v in settings.items():
                db.q("INSERT INTO setting_value (profile_id, key, value) VALUES (%s, %s, %s)", (pid, k, v))
            for i, s in slots.items():
                db.q("INSERT INTO robot_slot (profile_id, slot, model, x, y, yaw_deg) VALUES "
                     "(%s, %s, %s, %s, %s, %s)", (pid, i, s["model"], s["x"], s["y"], s["yaw"]))
        render(actor, db)
    return notes


# ---------------------------------------------------------------- real robots

def real_robots(actor=None):
    """{id: {host, user, cutter}}: from the database, else the copy render() last wrote."""
    try:
        with DB(actor) as db:
            rows = _real_rows(db)
        _write_real_file(rows)
        return {r["id"]: {"host": r["host"], "user": r["user"], "cutter": r["cutter"]} for r in rows}
    except Unavailable:
        try:
            data = json.loads(REAL_FILE.read_text())
        except (OSError, ValueError):
            return {}
        return {k: {"host": v.get("host"), "user": v.get("user") or "robot", "cutter": bool(v.get("cutter"))}
                for k, v in data.items() if isinstance(v, dict)}


def real_save(rid, host, user="robot", cutter=False, actor=None):
    with DB(actor) as db:
        db.q("INSERT INTO real_robot (id, host, ssh_user, cutter) VALUES (%s, %s, %s, %s) ON CONFLICT (id) DO UPDATE "
             "SET host = EXCLUDED.host, ssh_user = EXCLUDED.ssh_user, cutter = EXCLUDED.cutter",
             (rid, host, user or "robot", bool(cutter)))
        _write_real_file(_real_rows(db))


def real_remove(rid, actor=None):
    with DB(actor) as db:
        if db.q("DELETE FROM real_robot WHERE id = %s", (rid,)).rowcount == 0:
            raise ValueError(f"{rid} is not in the list")
        _write_real_file(_real_rows(db))


# ---------------------------------------------------------------- history and runs

def _slot_text(r):
    if not r:
        return "(none)"
    pose = f" at ({r['x']:g}, {r['y']:g}, {r['yaw_deg']:g}°)" if r.get("x") is not None else ""
    return r["model"] + pose


def _real_text(r):
    return f"{r['ssh_user']}@{r['host']}{', cutter' if r['cutter'] else ''}" if r else "(none)"


def describe(e, names):
    o, n = e["old_row"], e["new_row"]
    r = n or o
    t = e["tbl"]
    where = f"[{names.get(r.get('profile_id'), '#' + str(r.get('profile_id')))}] " if "profile_id" in r and t != "active_profile" else ""
    if t == "setting_value":
        return f"{where}{r['key']}: {o['value'] if o else '(default)'} -> {n['value'] if n else '(default)'}"
    if t == "robot_slot":
        return f"{where}slot {r['slot']}: {_slot_text(o)} -> {_slot_text(n)}"
    if t == "real_robot":
        return f"real robot {r['id']}: {_real_text(o)} -> {_real_text(n)}"
    if t == "active_profile":
        return (f"active profile: {names.get(o['profile_id'], '#' + str(o['profile_id'])) if o else '(none)'} -> "
                f"{names.get(n['profile_id'], '#' + str(n['profile_id'])) if n else '(none)'}")
    if t == "profile":
        if e["op"] == "INSERT":
            return f"profile {n['name']} created"
        if e["op"] == "DELETE":
            return f"profile {o['name']} deleted"
        return (f"profile {o['name']} renamed {n['name']}" if o["name"] != n["name"]
                else f"profile {n['name']}: notes changed")
    return f"{t} {e['op']}"


def history(limit=50, actor=None):
    with DB(actor) as db:
        rows = db.dicts("SELECT id, at, actor, tbl, op, old_row, new_row FROM change_log ORDER BY id DESC LIMIT %s",
                        (limit,))
        names = dict(db.all("SELECT id, name FROM profile"))
    for r in rows:
        r["text"] = describe(r, names)
        r["revertible"] = r["tbl"] in ("setting_value", "robot_slot", "real_robot", "active_profile")
    return rows


PKEYS = {"setting_value": ("profile_id", "key"), "robot_slot": ("profile_id", "slot"), "real_robot": ("id",)}
COLUMNS = {"setting_value": ("profile_id", "key", "value"),
           "robot_slot": ("profile_id", "slot", "model", "x", "y", "yaw_deg"),
           "real_robot": ("id", "host", "ssh_user", "cutter")}


def revert(entry_id, actor=None):
    """Put back what change ENTRY_ID changed (as a new change, itself in the log)."""
    with DB(actor) as db:
        e = db.dicts("SELECT tbl, op, old_row, new_row FROM change_log WHERE id = %s", (entry_id,))
        if not e:
            raise ValueError(f"no change {entry_id}")
        t, o, n = e[0]["tbl"], e[0]["old_row"], e[0]["new_row"]
        if t == "active_profile":
            if not o or not db.val("SELECT 1 FROM profile WHERE id = %s", (o["profile_id"],)):
                raise ValueError("that profile no longer exists")
            db.q("UPDATE active_profile SET profile_id = %s", (o["profile_id"],))
        elif t in PKEYS:
            r = o or n
            if "profile_id" in r and not db.val("SELECT 1 FROM profile WHERE id = %s", (r["profile_id"],)):
                raise ValueError("its profile no longer exists")
            keys = PKEYS[t]
            if o is None:  # it was added: remove it
                db.q(f"DELETE FROM {t} WHERE " + " AND ".join(f"{k} = %s" for k in keys), [n[k] for k in keys])
            else:
                cols = COLUMNS[t]
                db.q(f"INSERT INTO {t} ({', '.join(cols)}) VALUES ({', '.join(['%s'] * len(cols))}) "
                     f"ON CONFLICT ({', '.join(keys)}) DO UPDATE SET "
                     + ", ".join(f"{c} = EXCLUDED.{c}" for c in cols if c not in keys), [o[c] for c in cols])
        else:
            raise ValueError(f"a {t} change can't be reverted")
        r = render(actor, db)
        if r["errors"]:
            raise ValueError("; ".join(r["errors"]))
        return r


def run_begin(command, actor=None):
    """Record a scripts/fleet.sh run with the variables it runs with; its id, or None without a database."""
    commit = (git("rev-parse", "--short", "HEAD") or "").strip()
    if commit and (git("status", "--porcelain", "--untracked-files=no") or "").strip():
        commit += "-dirty"
    try:
        with DB(actor) as db:
            _, name = active(db)
            return db.val("INSERT INTO run (actor, command, profile, git_commit, env) VALUES (%s, %s, %s, %s, "
                          "%s::jsonb) RETURNING id", (actor or default_actor(), command, name, commit,
                                                      json.dumps(read_env_file())))
    except Unavailable:
        return None


def run_end(run_id, code, actor=None):
    try:
        with DB(actor) as db:
            db.q("UPDATE run SET finished_at = now(), exit_code = %s WHERE id = %s", (code, run_id))
    except Unavailable:
        pass


def runs(limit=30, actor=None):
    with DB(actor) as db:
        return db.dicts("SELECT id, started_at, finished_at, actor, command, profile, git_commit, exit_code, env "
                        "FROM run ORDER BY id DESC LIMIT %s", (limit,))


# ---------------------------------------------------------------- the web UI's view

def view(actor=None):
    """Everything the Configuration page shows, in one round trip."""
    try:
        with DB(actor) as db:
            cfg = load(db)
            r = render(actor, db)
            plist = profiles(db)
    except Unavailable as e:
        cfg = {"profile_id": None, "profile": None, "slots": {}, "settings": {}}
        env_vals = read_env_file()
        settings, slots, _ = import_env_vals(env_vals)
        cfg.update(settings=settings, slots=slots)
        r = {"source": "offline", "why": str(e), "errors": [], "warnings": []}
        plist = []
    errors, warnings = (r["errors"], r["warnings"]) if r["source"] == "database" else problems(cfg)
    return {"source": r["source"], "why": r.get("why", ""), "profile": cfg["profile"], "profiles": plist,
            "catalog": cat.SETTINGS, "sections": cat.SECTIONS, "settings": cfg["settings"],
            "num_robots": num_robots(cfg), "max_slots": cat.MAX_SLOTS,
            "slots": [dict(cfg["slots"].get(i) or {"model": GENERIC_SLOT_MODEL, "x": None, "y": None, "yaw": None},
                           slot=i, stored=i in cfg["slots"], ns=slot_ns((cfg["slots"].get(i) or {}).get(
                               "model", GENERIC_SLOT_MODEL), i)) for i in range(cat.MAX_SLOTS)],
            "errors": errors, "warnings": warnings, "db": DB_NAME}


# ---------------------------------------------------------------- check: catalog vs. compose

def check():
    text = (ROOT / "docker-compose.yml").read_text() + (ROOT / "basestation.compose.yml").read_text()
    used = {}
    for m in re.finditer(r"\$\{([A-Z][A-Z0-9_]*)(:?-)?([^}$]*)", text):
        used.setdefault(m[1], set()).add(m[3] if m[2] else None)
    bad = 0
    for s in cat.SETTINGS:
        k = s["key"]
        if k in cat.NOT_IN_COMPOSE:
            continue
        if k not in used:
            print(f"{k}: in the catalog but not in docker-compose.yml / basestation.compose.yml")
            bad += 1
            continue
        defaults = used[k] - {None}
        if k == "BASESTATION_RMW":  # ${BASESTATION_RMW:-${FLEET_RMW...}}: empty = FLEET_RMW
            continue
        if defaults and defaults != {s["default"]}:
            print(f"{k}: catalog default {s['default']!r}, compose {sorted(defaults)}")
            bad += 1
    for k in sorted(used):
        if k not in cat.BY_KEY and not cat.is_derived(k) and k not in ("DISPLAY", "VAR"):
            print(f"{k}: used by compose, not in scripts/fleet_settings.py")
            bad += 1
    print("catalog matches compose" if not bad else f"{bad} problem(s)")
    return 1 if bad else 0


# ---------------------------------------------------------------- command line

def _fmt_time(t):
    return t.astimezone().strftime("%Y-%m-%d %H:%M:%S") if t else ""


def _print_render(r):
    if r["source"] == "offline":
        print(f"[fleetcfg] {r['why']}; .env kept as it is" if not r.get("changed") else
              f"[fleetcfg] {r['why']}; .env made from the defaults", file=sys.stderr)
    for w in r.get("warnings", []):
        print(f"[fleetcfg] warning: {w}", file=sys.stderr)
    for e in r.get("errors", []):
        print(f"[fleetcfg] error: {e}", file=sys.stderr)


def cmd_show(a):
    v = view()
    if v["source"] == "offline":
        print(f"(database unreachable: {v['why']}; showing .env)")
    print(f"profile: {v['profile']}")
    for section in v["sections"]:
        print(f"\n[{section}]")
        for s in v["catalog"]:
            if s["section"] != section:
                continue
            val = v["settings"].get(s["key"])
            if val is None and s["advanced"] and not a.all:
                continue
            print(f"  {s['key']:26} {val if val is not None else s['default']!s:24} "
                  f"{'' if val is not None else '(default)'}")
    other = sorted(k for k in v["settings"] if k not in cat.BY_KEY)
    if other:
        print("\n[Not in the catalog]")
        for k in other:
            print(f"  {k:26} {v['settings'][k]}")
    print(f"\n[Robot slots]  NUM_ROBOTS={v['num_robots']}")
    for s in v["slots"]:
        if s["stored"] or s["slot"] < v["num_robots"]:
            pose = f"({s['x']:g}, {s['y']:g}, {s['yaw']:g}°)" if s["x"] is not None else "default pose"
            print(f"  {s['slot']}  {s['model']:12} {s['ns']:12} {pose:28} "
                  f"{'' if s['slot'] < v['num_robots'] else '(not started)'}")
    for e in v["errors"]:
        print(f"error: {e}")
    for w in v["warnings"]:
        print(f"warning: {w}")
    if not a.all:
        print("\n(advanced settings at their default hidden: --all)")


def cmd_get(a):
    try:
        with DB() as db:
            cfg = load(db)
    except Unavailable:
        cfg = dict(default_cfg(), settings=read_env_file())
    v = effective(cfg, a.key)
    if v is None:
        return 1
    print(v)


def cmd_set(a):
    updates = {}
    for kv in a.pairs:
        if "=" not in kv:
            raise ValueError(f"{kv}: KEY=VALUE")
        k, v = kv.split("=", 1)
        updates[k.strip()] = v
    _print_render(set_settings(updates))


def cmd_unset(a):
    _print_render(set_settings({k: None for k in a.keys}))


def cmd_robots(a):
    _print_render(set_settings({"NUM_ROBOTS": str(a.n)}))


def cmd_slot(a):
    pose = None
    if a.pose:
        try:
            x, y, yaw = (float(v) for v in a.pose.split(","))
        except ValueError:
            raise ValueError("--pose X,Y,YAW (m, m, degrees)") from None
        pose = {"x": x, "y": y, "yaw": yaw}
    _print_render(set_slot(a.slot, a.model, pose, a.no_pose, a.remove))


def cmd_render(a):
    r = render()
    _print_render(r)
    if not a.quiet and r["source"] == "database":
        print(f"[fleetcfg] .env {'written' if r['changed'] else 'unchanged'} (profile {r['profile']})", file=sys.stderr)
    return 1 if r["errors"] else 0


def cmd_profile(a):
    if a.op == "list":
        with DB() as db:
            active(db)
            for p in profiles(db):
                print(f"{'*' if p['active'] else ' '} {p['name']:24} {p['num_robots'] or '-':>3} robots  "
                      f"{p['settings']:>3} settings  {p['notes']}")
    elif a.op == "use":
        _print_render(profile_use(a.args[0]))
    elif a.op == "new":
        profile_new(a.args[0], a.source)
    elif a.op == "rename":
        profile_rename(a.args[0], a.args[1])
    elif a.op == "delete":
        profile_delete(a.args[0])
    elif a.op == "notes":
        profile_notes(a.args[0], " ".join(a.args[1:]))
    elif a.op == "export":
        print(json.dumps(profile_export(a.args[0] if a.args else None), indent=2))
    elif a.op == "import":
        print(f"imported as profile {profile_import(json.loads(Path(a.args[0]).read_text()), a.name)}")


def cmd_history(a):
    for r in reversed(history(a.n)):
        print(f"{r['id']:>6}  {_fmt_time(r['at'])}  {r['actor']:24}  {r['text']}")


def cmd_revert(a):
    _print_render(revert(a.id))


def cmd_runs(a):
    for r in reversed(runs(a.n)):
        code = "running" if r["exit_code"] is None and not r["finished_at"] else f"exit {r['exit_code']}"
        print(f"{r['id']:>5}  {_fmt_time(r['started_at'])}  {code:8}  {r['command']:24} profile {r['profile']}, "
              f"{r['env'].get('NUM_ROBOTS', '?')} robot(s), git {r['git_commit']}  ({r['actor']})")


def cmd_real(a):
    if a.op == "list":
        for rid, c in real_robots().items():
            print(f"{rid:12} {c['user']}@{c['host']}{'  cutter' if c['cutter'] else ''}")
    elif a.op == "set":
        cur = real_robots().get(a.id, {})
        real_save(a.id, a.host or cur.get("host") or f"cpr-{a.id.replace('_', '-')}.local",
                  a.user or cur.get("user") or "robot", cur.get("cutter", False) if a.cutter is None else a.cutter)
    elif a.op == "remove":
        real_remove(a.id)


def cmd_import_env(a):
    for n in import_env(a.file, a.profile):
        print(f"note: {n}")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("show")
    p.add_argument("--all", action="store_true", help="also advanced settings left at their default")
    p.set_defaults(fn=cmd_show)
    p = sub.add_parser("get")
    p.add_argument("key")
    p.set_defaults(fn=cmd_get)
    p = sub.add_parser("set")
    p.add_argument("pairs", nargs="+", metavar="KEY=VALUE")
    p.set_defaults(fn=cmd_set)
    p = sub.add_parser("unset")
    p.add_argument("keys", nargs="+")
    p.set_defaults(fn=cmd_unset)
    p = sub.add_parser("robots")
    p.add_argument("n", type=int)
    p.set_defaults(fn=cmd_robots)
    p = sub.add_parser("slot")
    p.add_argument("slot", type=int)
    p.add_argument("model", nargs="?")
    p.add_argument("--pose", help="X,Y,YAW: metres, metres, degrees")
    p.add_argument("--no-pose", action="store_true", help="the sim's default layout")
    p.add_argument("--remove", action="store_true", help="forget the slot (a300 if it is started)")
    p.set_defaults(fn=cmd_slot)
    p = sub.add_parser("render")
    p.add_argument("--quiet", action="store_true")
    p.set_defaults(fn=cmd_render)
    p = sub.add_parser("profile")
    p.add_argument("op", choices=["list", "use", "new", "rename", "delete", "notes", "export", "import"])
    p.add_argument("args", nargs="*")
    p.add_argument("--from", dest="source", help="new: copy this profile (default: the active one)")
    p.add_argument("--name", help="import: the new profile's name")
    p.set_defaults(fn=cmd_profile)
    p = sub.add_parser("history")
    p.add_argument("-n", type=int, default=30)
    p.set_defaults(fn=cmd_history)
    p = sub.add_parser("revert")
    p.add_argument("id", type=int)
    p.set_defaults(fn=cmd_revert)
    p = sub.add_parser("runs")
    p.add_argument("-n", type=int, default=20)
    p.set_defaults(fn=cmd_runs)
    p = sub.add_parser("real")
    p.add_argument("op", choices=["list", "set", "remove"])
    p.add_argument("id", nargs="?")
    p.add_argument("--host")
    p.add_argument("--user")
    p.add_argument("--cutter", action="store_true", default=None)
    p.add_argument("--no-cutter", dest="cutter", action="store_false")
    p.set_defaults(fn=cmd_real)
    p = sub.add_parser("import-env")
    p.add_argument("file")
    p.add_argument("--profile")
    p.set_defaults(fn=cmd_import_env)
    p = sub.add_parser("init")
    p.set_defaults(fn=lambda a: init())
    p = sub.add_parser("check")
    p.set_defaults(fn=lambda a: check())
    # used by scripts/fleet.sh
    p = sub.add_parser("run-begin")
    p.add_argument("command")
    p.set_defaults(fn=lambda a: print(run_begin(a.command) or ""))
    p = sub.add_parser("run-end")
    p.add_argument("id", type=int)
    p.add_argument("code", type=int)
    p.set_defaults(fn=lambda a: run_end(a.id, a.code))
    a = ap.parse_args()
    if a.cmd == "real" and a.op != "list" and not a.id:
        ap.error("real set/remove need an ID")
    try:
        sys.exit(a.fn(a) or 0)
    except (ValueError, Unavailable) as e:
        print(f"fleetcfg: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
